### ISSUE TITLE
getting-started/bookshelf/pubsub_worker does not implement health check handler

### ISSUE THREAD

**Issue by wuman** [GoogleCloudPlatform/golang-samples#10]
The pubsub_worker module in the bookshelf sample does not seem to implement a health check handler like the default module.  Is this an oversight or are worker modules not supposed to implement a health check handler?

**Comment by broady** [comment]
Worker modules have no technical difference to regular modules.

The worker module actually responds to requests on `/_ah/health` with the regular handler (that responds with the number of books processed). That constitutes a healthy request.

I think it'd be better to just use `appengine.Main()`, though.

**Comment by tbpg** [comment]
It's been a few years and an update for Bookshelf is in the works. Closing this.
