### ISSUE TITLE
testing: increase CI test speed via Dockerfile setup

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/golang-samples#1000]
The Dockerfiles at `testing/kokoro/docker` are very bare-bones, this means a number of setup steps from `testing/kokoro/system_tests.sh` are being performed on every test execution. On brief review, the following steps could be moved to the Dockerfile:

* Various non-sensitive environment variables
* gimmeproj installation
* go-junit-report installation
* gcloud installation (this would require special handling to address updates)

**Comment by tbpg** [comment]
Great idea! Definitely sounds good to me.
