### ISSUE TITLE
appengine: Remove appengine examples prior to go11x

### ISSUE THREAD

**Issue by sbuss** [GoogleCloudPlatform/golang-samples#1005]
Go 1.9 on App Engine Standard is deprecated and new deploys are no longer allowed. All users must migrate to `runtime: go111` or later. We can delete the old appengine examples and anything that mentions `goapp`.

**Comment by sbuss** [comment]
CC @juliehockett

**Comment by tbpg** [comment]
Big +1 to do this. But, we have to wait until all of the docs including these samples are removed.
