### ISSUE TITLE
appengine_flexible/redis: typo in REDIS_PASSSWORD (triple s)

### ISSUE THREAD

**Issue by samwize** [GoogleCloudPlatform/golang-samples#1023]
https://github.com/GoogleCloudPlatform/golang-samples/blob/062a01de21363adfa932d21780719fdb2b5e0d88/appengine_flexible/redis/app.yaml#L24

It should be `REDIS_PASSWORD`. This sample code wasted my time away.

**Comment by tbpg** [comment]
Thank you for the bug report and sorry for the typo. I'll fix it right away.
