### ISSUE TITLE
kms: no need to encode with base64

### ISSUE THREAD

**Issue by kenzht** [GoogleCloudPlatform/golang-samples#1037]
https://github.com/GoogleCloudPlatform/golang-samples/blob/ab8c5d453091dbbba3f3b8ddf910a4e7969f013f/kms/decrypt_rsa.go#L34

In the comment, the code encodes the cipherBytes using base64 but it is not needed when decrypting.

**Comment by tbpg** [comment]
Thank you for the bug report! I just sent #1038 to fix it.
