### ISSUE TITLE
pubsub: flaky test, bad error message

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/golang-samples#104]
```
main_test.go:59: got [0xc8204e2440 0xc8204e2460]; want the list with topic = "golang-samples-topic-example""
```

**Comment by broady** [comment]
```
main_test.go:94: got []; want a list with subscription "golang-samples-subscription"
```

**Comment by rakyll** [comment]
What is running against this project test account's pubsub?

We probably need isolation of names for these tests. I am not thinking of any other issue why they are flaky.

**Comment by broady** [comment]
Just these tests. But they might run concurrently.

**Comment by rakyll** [comment]
I will try to namespace everything and delete stuff I create only in the lifecycle of these tests.
