### ISSUE TITLE
appengine: please make your examples dyslexic friendly

### ISSUE THREAD

**Issue by ThePiachu** [GoogleCloudPlatform/golang-samples#1042]
I've recently switched from a previous version of GAE, back when the applications relied on `app` function and there was no `main` package. I glanced over the example and thought that `main()` just replaced `init()`, without noticing that in this line

https://github.com/GoogleCloudPlatform/golang-samples/blob/57656a1b0868ff961125829b725fb5802b434f30/appengine/go11x/helloworld/helloworld.go#L42

there is a `http.ListenAndServe` nested within a `log`, which meant I spent a few hours debugging my code that just returned `exit(1)` with no clear error log or anything.

It would be really good if the examples provided were more dyslexic friendly - avoiding nesting things, avoid being clever in code writing, etc. I know golang has a lot of boring error handling and what have you, but it's better that the example file has a few extra newlines than someone missing something important...

**Comment by tbpg** [comment]
Hi @ThePiachu. Thank you, this is good feedback. Sorry for the trouble.

As I'm sure you know, `func main` is the entrypoint for Go binaries. It's what runs when your app runs. So, in some cases, it can make sense to move something from `init` into `main`, but not always. `init` functions will run during package initialization time, before the `main` function is called.

To have an App Engine app that successfully serves requests, you'll need to start an HTTP server. The most common way to do that is with `http.ListenAndServe`. You can run the app locally or deploy it to App Engine (with an `app.yaml` file).

cc @grayside - what do you think of updating the samples to split out the `http.ListenAndServe` call? We have this pattern in a few places, so want to make sure to update it the right way.
