### ISSUE TITLE
Go 11x example is **misleading**

### ISSUE THREAD

**Issue by ThePiachu** [GoogleCloudPlatform/golang-samples#1043]
I recently converted from go1 (1.9?) to go111, and as it turns out, the go 11x example provided in this repository is **misleading**. More specifically, [the main function](https://github.com/GoogleCloudPlatform/golang-samples/blob/57656a1b0868ff961125829b725fb5802b434f30/appengine/go11x/helloworld/helloworld.go#L31), while letting you run a basic application, will screw you over when you create a more complex application.

See this issue on StackOverflow: https://stackoverflow.com/a/58478111/953732 . By following the example and using `http.ListenAndServe`, it didn't let me use context for Datastore, resulting in error `textPayload: "2019/10/20 22:32:46 http: panic serving 127.0.0.1:16051: not an App Engine context`. Apparently, the **proper** way of starting appengine is

```
func main() {
    appengine.Main()
}
```

Which will let you use the appengine like you used to in go1 and access the `datastore` with a proper context.

Please update the examples not to direct people down a solution that will work for only the most basic applications.

**Comment by tbpg** [comment]
Hi @ThePiachu. Thank you for filing this issue.

There are two Datastore packages you can use:
* https://godoc.org/cloud.google.com/go/datastore: Can be used for second generation App Engine Standard apps (Go 1.11+). Go 1.9 was the last "first generation" runtime for Go.
* https://godoc.org/google.golang.org/appengine/datastore: Must be used in first generation apps. It _can_ be used in Go 1.11, but you have to continue to use the rest of the `google.golang.org/appengine` set of packages (including the context). For Go 1.12 and beyond, these App Engine-specific APIs don't work.

Sorry this was unclear. If you switch to using cloud.google.com/go/datastore, you won't run into this problem. It also means you can write your app the same way you would write it anywhere else (say, if you were deploying this in a VM on GCE or using Cloud Run). Second generation runtimes avoid the need for (most) App Engine-specific code. This is described a bit here: https://cloud.google.com/appengine/docs/standard/go111/go-differences#migrating-appengine-sdk

I hope that helps.
