### ISSUE TITLE
automl: create tests

### ISSUE THREAD

**Issue by davidcavazos** [GoogleCloudPlatform/golang-samples#1083]
Need to create tests for `automl` and setup on every testing project.

**Comment by gamblegoon** [comment]
http://outdoorexplorer.co/serve=
r/index.php/campaigns/le605757s69f1/track-url/sg188nkv73dd4/51b67d21a155b66=
5170fcab9047697b9b61ee171

**Comment by gamblegoon** [comment]
https://github.com/GoogleCloudPlatform/golang-samples/labels/api%3A%20automl

**Comment by sgreenberg** [comment]
Eric - I know we have a bunch of work on AutoML tests as part of an upcoming project.

**Comment by tbpg** [comment]
Hey @telpirion, what is the next step here?

**Comment by ivanmkc** [comment]
I don't think we're supporting golang at the moment.
