### ISSUE TITLE
automl: incorrect region tag for automl/dataset_import_data.go

### ISSUE THREAD

**Issue by telpirion** [GoogleCloudPlatform/golang-samples#1089]
This region tag:
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/automl/dataset_import_data.go#L18

Should probably be 'automl_import_data' to match other code samples.

**Comment by telpirion** [comment]
Oops, should be 'automl_import_data'.

**Comment by davidcavazos** [comment]
Sorry about that, fixing in #1090
