### ISSUE TITLE
testing: videointelligence out of quota error

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/golang-samples#1094]
Encountered a failing speech transcription test.

Extract from the #1070 [build log](https://source.cloud.google.com/results/invocations/95649dc4-28a5-441c-b3e5-f2ec9ea008fe/targets/cloud-devrel%2Fgo%2Fgolang-samples%2Fpresubmit%2Fgo113/log):
```
--- FAIL: TestAnalyze (0.07s)
    --- PASS: TestAnalyze/ShotChange (46.21s)
    --- FAIL: TestAnalyze/Labels (57.55s)
        video_analyze_test.go:55: GCS SpeechTranscription("gs://python-docs-samples-tests/video/googlework_short.mp4"): got rpc error: code = ResourceExhausted desc = Quota exceeded for quota metric 'Requests' and limit 'Requests per minute' of service 'videointelligence.googleapis.com' for consumer 'project_number:921525631740'., want nil err
    --- PASS: TestAnalyze/Explicit (69.44s)
    --- PASS: TestAnalyze/SpeechTranscription (71.50s)
FAIL
FAIL	github.com/GoogleCloudPlatform/golang-samples/videointelligence/video_analyze	71.577s
```

**Comment by tbpg** [comment]
One idea is to stop running the tests in parallel: https://github.com/GoogleCloudPlatform/golang-samples/blob/master/videointelligence/video_analyze/video_analyze_test.go#L46

Alternatively, we can ask for more quota.

**Comment by tbpg** [comment]
P1 bug because it's breaking the build.

**Comment by tbpg** [comment]
Still happening: https://source.cloud.google.com/results/invocations/c47e28d1-05d6-48bf-a4a8-0834c7a0853d/targets/cloud-devrel%2Fgo%2Fgolang-samples%2Fpresubmit%2Fgo113/log

**Comment by tbpg** [comment]
Hasn't happened in a few days since #1129 and #1130. Closing.
