### ISSUE TITLE
testing: out of date `go.mod` provides misleading instruction in github

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/golang-samples#1123]
When a PR fails testing, the status message displayed in Github says it's a "Kokoro CI infrastructure error" and requests a `kokoro:force` label be added:

![Screen Shot 2019-12-11 at 9 51 52 AM](https://user-images.githubusercontent.com/283489/70646614-22562180-1bfc-11ea-953c-2d77b138b52c.png)

This is not true in the case where the go.mod file is out of date with respect to changes made to a new sample which is not itself a sub-module.

Here's an example of the failing command, I'm not sure what is running this diff:

```
diff --git a/go.mod b/go.mod
index ba2b181..670d7fb 100644
--- a/go.mod
+++ b/go.mod
@@ -20,6 +20,7 @@ require (
 	github.com/bradfitz/gomemcache v0.0.0-20190913173617-a41fca850d0b
 	github.com/dgrijalva/jwt-go v3.2.0+incompatible
 	github.com/eclipse/paho.mqtt.golang v1.2.0
+	github.com/fatih/color v1.7.0
 	github.com/fluent/fluent-logger-golang v1.4.0
 	github.com/go-sql-driver/mysql v1.4.1
 	github.com/gofrs/uuid v3.2.0+incompatible
@@ -37,6 +38,8 @@ require (
 	github.com/linkedin/goavro/v2 v2.9.7
 	github.com/mailgun/mailgun-go/v3 v3.6.2
 	github.com/mailjet/mailjet-apiv3-go v0.0.0-20190724151621-55e56f74078c
+	github.com/mattn/go-colorable v0.1.4 // indirect
+	github.com/mattn/go-isatty v0.0.10 // indirect
 	github.com/philhofer/fwd v1.0.0 // indirect
 	github.com/sendgrid/smtpapi-go v0.6.0 // indirect
 	github.com/tinylib/msgp v1.1.0 // indirect
```

**Comment by tbpg** [comment]
I added this check in #1114 because we were having problems when the `go.mod` wasn't updated. But, it sounds like that is still causing issues. Perhaps we should do a `git stash` after running the diff to avoid the caching issue?

When `root` updates the `go.mod`, it takes ownership and Kokoro can't cache the file, leading to the "infrastructure" error.

**Comment by grayside** [comment]
Flagging this as out-of-date seems valuable but the message is poor. Maybe `chown` the file back?

**Comment by tbpg** [comment]
This is now fixed -- when the `go.mod` is out of date, Kokoro shows a normal failure, not an infrastructure failure.
