### ISSUE TITLE
CONTRIBUTING: a few more things for the style guide

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/golang-samples#1133]
A few questions that came up when working behind @bradmiro's shoulder:

- [ ] guidance on resource names and that they should use something like `tc.ProjectID + "-golang-samples-myapi-mysnippet`, clean up before + after. Avoid uuids and timestamp-based resource names because they tend to leak when not cleaned up properly.
- [ ] when to use testutil.SystemTest vs testutil.EndToEndTest (any test that typically takes more than N minutes? maybe N=2?)

/cc @kurtisvg

**Comment by grayside** [comment]
For `tc.ProjectID + "-golang-samples-myapi-mysnippet`, isn't golang-samples already in the tc.ProjectID output?

For SystemTest vs. EndToEndTest, I've had a few cases where the distinction has been gcloud availability.

**Comment by tbpg** [comment]
Another item:

Use `flag.String` instead of `flag.StringVar`.

```
$ grep -ERl 'flag\.[a-zA-Z]+Var' .
./dialogflow/detect_intent/detect_intent.go
./dialogflow/context_management/context_management.go
./dialogflow/entity_type_management/entity_type_management.go
./dialogflow/session_entity_type_management/session_entity_type_management.go
./dialogflow/intent_management/intent_management.go
./bigtable/quickstart/main.go
./dataproc/quickstart/quickstart.go
./storage/gcsupload/gcsupload.go
./storage/objects/main.go
```

**Comment by tbpg** [comment]
Another item:

Skip tests if `GOLANG_SAMPLES_PROJECT_ID` is unset. This is related to using `testutil`, which is already documented, but it would be good to make it explicit.

Mentioned by @sethvargo in #1371.

**Comment by tbpg** [comment]
Another item:

* Don't use reflection. Call functions directly.

Mentioned by @codyoss in #985.
