### ISSUE TITLE
logging: simplelog is not very simple

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/golang-samples#1149]
From @kaihendry on #802:

> I'm trying to simply log JSON so that it appears structured in stackdriver.
> I must say https://github.com/GoogleCloudPlatform/golang-samples/blob/master/logging/simplelog/simplelog.go is far from simple. And it puzzles my why I need to put the [PROJECT_ID to even use the logger](https://cloud.google.com/logging/docs/setup/go). Bizarre.

@tbpg can/should we simplify this to infer project ID from the environment (e.g. ADC)?

**Comment by tbpg** [comment]
There is some effort going on to be able to infer the project ID from the environment, but for the Go clients we decided to be explicit with passing the project ID. That way, most of the time, it's clear what project is being used. However, it can definitely be a pain to get the project ID depending on your environment... I agree it's not great, but we also can't change the API at this point. So, I'm going to close this.

**Comment by kaihendry** [comment]
Do you have any examples of logging code that can easily deploy to any GCP product?

Am I struggling to avoid hard coding here...

**Comment by tbpg** [comment]
Sorry for the slow response. You should be able to use https://pkg.go.dev/cloud.google.com/go/compute/metadata?tab=doc#ProjectID to get the project ID while running on GCP. I'd first check for the `GOOGLE_CLOUD_PROJECT` env var, then check that, and error if you still don't have a project.
