### ISSUE TITLE
storage: separate each sample into a separate file

### ISSUE THREAD

**Issue by crwilcox** [GoogleCloudPlatform/golang-samples#1157]
Each sample should be in a standalone file. This workitem is to track that work.

**Comment by IlyaFaer** [comment]
Me and @AlisskaPie will do this

**Comment by IlyaFaer** [comment]
We separated the samples (with our own separator-script, just some manual work left)

I suppose style and formatting rules in [CONTRIBUTING.md](https://github.com/GoogleCloudPlatform/golang-samples/blob/master/CONTRIBUTING.md) are actual, and we should follow them!? Including `Don't initialize one client for the entire set of samples and pass it as an argument. Each sample should initialize its own client/service`?

cc/ @tritone, @frankyn

**Comment by tbpg** [comment]
Yes, please!

**Comment by IlyaFaer** [comment]
@tbpg, I suppose for now all the samples are separated. Do we have anything more to do for this issue, or it can be closed?

P.S. we can probably take part in writing missing samples (which we have on other languages), but these are gonna be separate issues I assume.

**Comment by tbpg** [comment]
Thank you! I'll close this. Please work with @tritone, @frankyn, and @JesseLovelace (sorry if I'm missing anyone) on any additional work.
