### ISSUE TITLE
cloudsql: author sample for postgres

### ISSUE THREAD

**Issue by crwilcox** [GoogleCloudPlatform/golang-samples#1158]
Author sample for postgresql modeled after mysql example at https://github.com/GoogleCloudPlatform/golang-samples/pull/1085

**Comment by tbpg** [comment]
For the record, we have some runtime-specific Postgres samples: https://github.com/GoogleCloudPlatform/golang-samples/search?q=postgres&unscoped_q=postgres. Might help with writing a runtime-agnostic sample.

**Comment by tbpg** [comment]
Done in #1563.
