### ISSUE TITLE
testing: go vet fails with nested sub-modules

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/golang-samples#1161]
#1151 surfaced a problem with how go vet handles nested sub-modules.

Fails:
```
➜  go vet ./cloudsql/...          
go: warning: "./cloudsql/..." matched no packages
no packages to vet
```

```
➜  go vet ./cloudsql/mysql/database-sql/...
go: directory cloudsql/mysql/database-sql is outside main module
```

Succeeds:
```
➜  cd ./cloudsql/mysql/database-sql 
➜  go vet ./...
```

This is reproducible in the /run directory by creating a structure like this:

```
run/
├── editor
│   ├── editor
│   │   ├── Dockerfile
│   │   ├── go.mod
│   │   ├── go.sum
│   │   ├── ...
│   ├── sentiment
│   │   ├── Dockerfile
│   │   ├── go.mod
│   │   └── main.go
│   ├── spellcheck
│   │   ├── Dockerfile
│   │   ├── go.mod
│   │   └── main.go
```

Possible Solutions:

* Adjust our script to descend into every sub-module before running `go vet ./...`.
* Detect "matched no packages" and suppress error (go vet uses the same error code for a failed test as a failed execution, so this requires string matching stderr)
* Denylist on certain directories
* Fix go tool? Not clear what that would mean so probably would take too long.

**Comment by tbpg** [comment]
I'd prefer to actually run `go vet` on everything. So, I'd prefer not to do (2) or (3).

cc @jayconrod for (4).

That leaves us with (1). Which seems like it would work, but be a little annoying.

**Comment by jayconrod** [comment]
This seems like the right way to go:

> Adjust our script to descend into every sub-module before running go vet ./....

Modules in subdirectories are separate workspaces with separates sets of packages available (perhaps some of the same packages at different revisions). A single command can't match packages in more than one workspace.

**Comment by grayside** [comment]
Here's some shell script.

1. Only error on certain classes of error. This would be easier if go vet had a different exit code for nothing-to-check:

```sh
set +e
# Bash 4+ incantation to output stdout to terminal as normal
# and capture stderr to a variable
{ vetError=$(go vet $TARGET 2>&1 1>&$out); } {out}>&1
set -e

echo $vetError
if [[ $vetError != *"no packages to vet"* ]]; then
  exit 1
fi
```

2. Descend into submodules, because they are being skipped with or without an error:

```
for i in $(find $(dirname $TARGET) -name "go.mod")
do
  mod="$(dirname $i)"
  echo "Running 'go vet' in $mod"
  pushd "$mod"
  go vet ./...
  popd
done
```

I can fold this up into a PR to `testing/kokoro/system_tests.sh` if this approach is basically sound.

**Comment by tbpg** [comment]
Option 2 LGTM. Not sure if there are hidden Bash pitfalls, but we'll find out!

**Comment by grayside** [comment]
To clarify, fix 1 is needed because top-level directories that only contain sub-modules will cause the test to fail, fix 2 is needed to actually test submodules.

**Comment by tbpg** [comment]
Got it. Maybe we could use `find` to make sure there are `.go` files in the directory before running `vet` on it? Either way, probably easier to solidify what exactly is happening in a PR.

**Comment by grayside** [comment]
Yep, I'll send a PR.

**Comment by cyrusv** [comment]
I am experiencing a similar problem with `go test ./...` -- tests in submodules are not being run!
