### ISSUE TITLE
pubsub: Subscription has no field or method Name

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/golang-samples#117]
Build is broken:
https://travis-ci.org/GoogleCloudPlatform/golang-samples/builds/159763624

```
pubsub/subscriptions/main.go:43: sub.Name undefined (type *"cloud.google.com/go/pubsub".Subscription has no field or method Name, but does have "cloud.google.com/go/pubsub".name)
```

/cc @rakyll

**Comment by rakyll** [comment]
Already closed via https://github.com/GoogleCloudPlatform/golang-samples/commit/b5f7a025804e34e9721b8082386a40af86b81b85.
