### ISSUE TITLE
testing: go submodule testing incomplete

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/golang-samples#1180]
Follow-up on #1161.

## Problem

It seems as though `go list` never recurses into sub-modules, as `go vet`, `go fmt`, and `go test` all skip sub-modules. At the same time, the `system_test.sh` file is trending towards unmanageably complicated.

## Impact

Samples implemented as self-contained go modules (such as most Cloud Run samples, some Functions samples, Getting Started samples, a couple appengine)  are not properly tested on nightly jobs, still verifying what is happening in PRs. This seems like it should block new module-based samples except where urgent and manual test execution is an acceptable trade-off.

## Solution

I think we should consider a rewrite to standardize practices and improve readability.

Some initial options:

* Option 1: Decompose the BASH script into a more functional-style script
* Option 2: Rewrite most of this in Go, with the intention to invoke from trampoline with `go run`
* Option 3: Incremental fixes to the `system_tests.sh` script.

We are currently pursuing **Option 3**.

**Comment by grayside** [comment]
I've done some experimenting with Option 1, here's how I think it might go:

### Utility Functions

These standardize how the codebase is traversed and scanned:

```sh
function eachModule {
  >&2 echo "Running eachModule in ${PWD} with command ($@)..."
  for m in $(find . -name go.mod); do
    dir="$(dirname $m)";
    pushd $dir > /dev/null;
    >&2 echo "-> Running in ${PWD}...";
    $@ "$dir";
    popd > /dev/null;
  done
}

function eachChangedDirectory {
  >&2 echo "Running eachChangedDirectory in ${PWD}..."
  for d in $CHANGED_DIRS; do
    # Filter out directories that don't exist (the current PR deleted them).
    if [ -d "$d" ]; then
      pushd $d > /dev/null;
      >&2 echo "-> Running in ${PWD}...";
      $@ "$d";
      popd > /dev/null;
    fi
  done
}

function eachChangedModule {
  eachChangedDirectory eachModule $@
}

function flatten {
  echo "$1"
}

function changedPackages {
  eachChangedDirectory flatten | xargs printf "./%s/... "
}
```

### Scanner functions

These are the tasks we want to perform as part of the pipeline:

```sh
function checkGoModuleSyncStatus {
    set -x;
    go mod tidy;
    git diff go.mod | tee /dev/stderr | (! read)
    [ -f go.sum ] && git diff go.sum | tee /dev/stderr | (! read)
    set +x;
}

function goVet {
  set -x;
  go vet ./...;
  set +x;
}

function goFmtDiff {
  set -x;
  diff -u <(echo -n) <(gofmt -d -s .)
  set +x;
}	

function goTest {
  set -x;
  2>&1 go test -timeout $TIMEOUT -v . $1 | tee $OUTFILE
  set +x;
}
```

### Usage

Now that the logic is neatly encapsulated, we could move some of it to a separate file for testing if we wanted. In the meantime, we can now focus our reasoning about tasks to perform:

```
eachModule checkGoModuleSyncStatus

if [[ $RUN_ALL_TESTS = "1" ]]; then
  echo "Running all tests"
  TEST_TARGET="./..."
else
  TEST_TARGET=$(changedPackages)
  if [[ -z "${TEST_TARGET// }" ]]; then
    TEST_TARGET=""
    echo "Only running root tests"
  fi
fi

goTest $TEST_TARGET
```

**Comment by tbpg** [comment]
I'm hesitant to spend a lot of time on a big rewrite. If we do, I think I'd prefer to add some Go tooling into the mix, rather than add shell functions and so on. Want to minimize the amount of Bash people need to know. Might be different once we're in the weeds rewriting it.

Also, it's tricky to update and keep Kokoro happy.

Happy to review any PRs.

**Comment by grayside** [comment]
After some further thought, I've decided to decouple the idea of tech debt in system_tests.sh from the lack of sub-module support. I've also found a good number of the Functions and getting started samples are also wrapped in modules.

**Comment by grayside** [comment]
Changes sufficient to address this have been merged, I will file follow-ups for new errors from the nightly build.

**Comment by tbpg** [comment]
I enabled the Cloud Run API and sent #1214 to skip the failing storage test.
