### ISSUE TITLE
all: make all snippets tests

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/golang-samples#124]
Our current approach to test these sample programs is tedious and repetitive. I end up writing the same amount of boring code again and again; first to construct the program and then to test the pieces of the same program.

Rather than writing an actual main package, we should consider the entire repo to be test files that will both illustrate how to use the cloud packages and to assert them.

Since we will tag the reference code with [START *] and [END *], I do think that the tests will be stll readable.

I wanna start doing this when writing snippets for the storage/objects.

/cc @broady

**Comment by broady** [comment]
No, sorry, please continue to write them as-is. I would explain more in person but I'm away for the next week.
