### ISSUE TITLE
testing: add GitHub Actions

### ISSUE THREAD

**Issue by tbpg** [GoogleCloudPlatform/golang-samples#1247]
Let's add GitHub Actions for a few tests:

- [ ] Code is formatted with ~~`gofmt`~~ [edit:] `goimports` (does formatting + imports).
- [ ] Code compiles.
- [ ] Proper license headers.

These all come up relatively frequently, especially with new contributors. An Action is very clear (and fast!) about what the issue was and we should be able to include the command to fix it. On the other hand, test logs are not clear for new devs when one of these issues pop up.

The license check can probably be general and apply to any Google repo. @JustinBeckwith has brought this up a few times.

The others would be helpful for our Go repos.

@bcoe, is this something you could help out with?

cc @codyoss, who may also be interested.

**Comment by codyoss** [comment]
I have been meaning to take a look into this space more, would love to give it a shot.

**Comment by tbpg** [comment]
Thank you!
