### ISSUE TITLE
Request Bazel based sample to use golang Cloud SDK

### ISSUE THREAD

**Issue by rmgogogo** [GoogleCloudPlatform/golang-samples#1274]
Request Bazel based sample to use golang Cloud SDK

**Comment by tbpg** [comment]
Thanks for the feature request. However, this seems like something that should be covered by Bazel. This repo is for Go samples on cloud.google.com (they are embedded in the docs). You may also have more luck asking specific questions like this on StackOverflow (be sure to include the exact package/module you're trying to use and what you've tried so far).

Closing this for now, but let us know if you spot another issue.
