### ISSUE TITLE
Pub/Sub: update publish with batch settings sample to queue 10 messages

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/golang-samples#1294]
Please update [this Go sample](https://github.com/GoogleCloudPlatform/golang-samples/blob/master/pubsub/topics/publish_settings.go) to match other publish with batch settings samples [here](https://cloud.google.com/pubsub/docs/publisher#batching), by publishing x number of messages instead of 1.

**Comment by AlisskaPie** [comment]
I'll take care of it
