### ISSUE TITLE
functions: [Go113 runtime] Environment Variables

### ISSUE THREAD

**Issue by TuSKan** [GoogleCloudPlatform/golang-samples#1300]
Can't get GCP_PROJECT form os env vars on Go113 runtime as mention for others runtimes on [https://cloud.google.com/functions/docs/env-var#environment_variables_set_automatically](url)
```
// projectID is set from the GCP_PROJECT environment variable, which is
// automatically set by the Cloud Functions runtime.
var projectID = os.Getenv("GCP_PROJECT")
```
The same code run on Go111 runtime.

**Comment by tbpg** [comment]
This is documented here: https://cloud.google.com/functions/docs/env-var#nodejs_10_and_subsequent_runtimes

But, we should definitely get that sample updated -- that's a bug. Thank you for reporting this!

**Comment by TuSKan** [comment]
Sorry, I didn’t see that. Thank you very much to share.

**Comment by tbpg** [comment]
All good! Sorry it wasn't more clear. Reopening so we can track fixing that comment.

**Comment by grant** [comment]
> Reopening so we can track fixing that comment.

Created a PR to fix the comment.
