### ISSUE TITLE
securitycenter: unknown field propertyDataTypes in securitycenter.Finding when unmarshalling

### ISSUE THREAD

**Issue by nulldowntime** [GoogleCloudPlatform/golang-samples#1323]
https://github.com/GoogleCloudPlatform/golang-samples/blob/8dfef3645ffe8fc9e5eb79354cee2f6d8bd10521/securitycenter/notifications/receive_notifications.go#L44

I had to do this to make it work: 
```
um := &jsonpb.Unmarshaler{AllowUnknownFields: true}
um.Unmarshal(bytes.NewReader(msg.Data), notificationMessage)
```

otherwise I get this for all messages:

> unknown field \"propertyDataTypes\" in securitycenter.Finding

and for some also this:

> unknown field \"workflowState\" in securitycenter.Finding

**Comment by codyoss** [comment]
cc @tdh911

**Comment by codyoss** [comment]
This was a backend issue which has since been resolved.
