### ISSUE TITLE
how to get URL for object in storage bucket :(

### ISSUE THREAD

**Issue by ORESoftware** [GoogleCloudPlatform/golang-samples#1333]
very unclear how to get the url for an object in a storage bucket :(

```golang

bucketName := "images.eng.cm.com"
filePath := fmt.Sprintf("avatars/%s", user.ID)

client, err := storage.NewClient(c.GetDefaultCtx())

if err != nil {
    return err
}

bucket := client.Bucket(bucketName)

bucketObj := bucket.Object(filePath)

w := bucketObj.NewWriter(c.GetDefaultCtx())

w.ContentType = "image/jpeg"

_, err = w.Write([]byte(base64str))

if err != nil {
    return err
}

err = w.Close()

if err != nil {
    return err
}

user.Avatar = null.String{
    String:  "", // !!! here I want to put the URL to the bucket object
    Valid:  true,
}

return err
```

there is my code - anyone know how to get the URL for the object in the bucket?

**Comment by ORESoftware** [comment]
also, very sadly the bucket instance does not have a means to retrieve the name:

![Screenshot from 2020-04-09 12-05-07](https://user-images.githubusercontent.com/11139560/78931425-ca6ce180-7a5a-11ea-9355-be176cd558bc.png)

is that right?

so in order to get the URL, I had to do this:

```golang
func getStorageObjectURL(bucketName string, objName string) string {
  return fmt.Sprintf("http://storage.googleapis.com/%s/%s", bucketName, objName)
}
```

the above seems unnecessary, I should be able to call:

```golang
bucket.Object(filePath).getURL()
```

please

**Comment by codyoss** [comment]
Are you looking for the download link? If so you can use the:
```go
attrs, _ "= client.Bucket(...).Object(...).Attrs(...)
fmt.Println(attrs.MediaLink)
```
https://pkg.go.dev/cloud.google.com/go/storage?tab=doc#ObjectAttrs

**Comment by ORESoftware** [comment]
wow that could not be more obvious ;) fml
