### ISSUE TITLE
storage/service_account/hmac: TestDeleteKey failed

### ISSUE THREAD

**Issue by tbpg** [GoogleCloudPlatform/golang-samples#1347]
```
TestDeleteKey: hmac_test.go:152: Error in deleteHMACKey: Delete: context deadline exceeded TestDeleteKey: hmac_test.go:156: State of key is INACTIVE, should be DELETED
```

We should probably extend the context deadline on all of the storage samples.

(Filing this as a fake Build Cop Bot issue to avoid having a duplicate created.)

**Comment by tritone** [comment]
Have the deadlines been flaky on anything aside from the SA HMAC samples? I put up a PR to extend the deadlines to 60s for all of these, but I'm not sure if it's necessary to modify additional samples as well. Timeouts longer than 10s seem pretty unrealistic for production use for many methods.

**Comment by tbpg** [comment]
Mentioned on the PR, but let's start with these and we can extend the others if needed.

Thank you for the quick fix!
