### ISSUE TITLE
run/pubsub: Add e2e test coverage

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/golang-samples#1350]
This sample does not have end-to-end test coverage. This coverage should be added.

A direct health check is minimal, but since this sample demonstrates handling message from Pub/Sub it may be worth seeing if the following flow could be done without too much flakiness:

* Deploy the Cloud Run service
* Create a Pub/Sub topic
* Create a Pub/Sub subscription
* Publish a message to the Pub/Sub topic
* Check the log output

This issue is blocked on finding a solution for testing log details in #696.

**Comment by tbpg** [comment]
@grayside what is the next step here? #696 was resolved.

**Comment by grayside** [comment]
That's great news! The next step is to create an e2e test that publishes a message to a pub/sub topic, then pull logs to compare expected output from the service.

**Comment by grayside** [comment]
The current test is at https://github.com/GoogleCloudPlatform/golang-samples/blob/main/run/testing/pubsub.e2e_test.go

We could take two approaches: add the necessary resource creation as part of a test, or leverage https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/cloud_run_service_pubsub/main.tf with an extra post-processing step to make hard-coded identifiers usable in the golang-samples testing projects.

The idea of making complex e2e tests also test that our terraform sample produces a functional service appeals to me, but the cross-repo dependency and need for transforms sounds complicated.

Curious what others think. cc @muncus

**Comment by telpirion** [comment]
Looks like there is now a test in that folder. Closing this issue.
