### ISSUE TITLE
run/logging-manual: Add e2e test coverage

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/golang-samples#1351]
This sample does not have end-to-end test coverage. This coverage should be added.

The existing unit test checks we write the expected log. The essential benefit of an end-to-end test is confirmation that Cloud Logging is successfully parsing the data structure. There is a node.js implementation of this test in [nodejs-docs-samples:/run/logging-manual](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/run/logging-manual).

This issue is blocked on finding a solution for testing log details in #696.

**Comment by tbpg** [comment]
@grayside what is the next step here? #696 was resolved.

**Comment by grayside** [comment]
That's great news! The next step is to create an e2e test that publishes a message to a Pub/Sub topic to which this sample is subscribed, then check the expected log output.

**Comment by grayside** [comment]
Logging samples are being re-thought in the context of structure logging. Will leave sorting out testing to that effort.
