### ISSUE TITLE
firestore: quickstart sample doesn't have appropriate imports

### ISSUE THREAD

**Issue by IlyaFaer** [GoogleCloudPlatform/golang-samples#1360]
See [this issue](https://github.com/googleapis/google-cloud-go/issues/1940) for context.

@tbpg, should we separate samples into standalone files and add imports as we did in Storage?

**Comment by tbpg** [comment]
I'm not sure the best way to do this. The Firebase samples generally use a different style that doesn't include imports (I think so they can show how to various types of queries succinctly). But, for a quickstart, I think we should show more detail.

Looking at the [tutorial](https://cloud.google.com/firestore/docs/quickstart-servers#go_1), it is a bit confusing that the snippets shown on the page aren't wrapped in declarations, therefore don't compile if copied & pasted as-is.

So, let's not rewrite all of the Firestore samples, at least for now. But, let's clean this one up so the tutorial shows function declarations and imports.

@BenWhitehead, does that sound OK to you?

**Comment by BenWhitehead** [comment]
For now, lets only add the imports for the quick start by adding a region tag around the imports of `fs_initialize` then the docs site will pull the imports into that snippet before the NewClient code.

**Comment by IlyaFaer** [comment]
Imports added into the samples with https://github.com/GoogleCloudPlatform/golang-samples/pull/1407
