### ISSUE TITLE
datastore: GetMulti example gives an error

### ISSUE THREAD

**Issue by rumsrami** [GoogleCloudPlatform/golang-samples#1362]
When using this line to batch get entities from datastore it generates this error:

datastore: keys and dst slices have different length

This should be changed to
var tasks []*Task
tasks := make([]*Task, len(taskKeys))

https://github.com/GoogleCloudPlatform/golang-samples/blob/fe6277fb1aa032d9fd61206138fd0fc9ce8fb4fc/datastore/snippets/snippet_test.go#L265

**Comment by codyoss** [comment]
Thanks for the report!
