### ISSUE TITLE
speech: Modifying livecaption.go to just return transcription without all the other stuff

### ISSUE THREAD

**Issue by DennisFaucher** [GoogleCloudPlatform/golang-samples#1369]
First of all. OMG this actually works. Beautiful. I talk into my mic, it streams the audio to Google Cloud, transcribes and keeps sending back the transcribed text real time. What code changes would I ned to make to just display the transcribed text and nothing else? TIA.

Sample (From my Live Aid Wembley program)

Result: alternatives:<transcript:"**when Bob Geldof first came to my office to discuss this event I thought he was joking when Maurice Jones joined Bob and myself for the next meeting it suddenly became reality let's go For Broke we said let's raise as much money as possible and now seems reality**" confidence:0.9714806 > is_final:true result_end_time:<seconds:21 nanos:650000000 >

**Comment by tbpg** [comment]
I'm glad it worked!

You'll want to modify these lines:

https://github.com/GoogleCloudPlatform/golang-samples/blob/719088e61bd13c9925b9673a5115491f9e195411/speech/livecaption/livecaption.go#L104-L106

Here is the type that is returned by `Recv`: https://pkg.go.dev/google.golang.org/genproto/googleapis/cloud/speech/v1?tab=doc#StreamingRecognizeResponse

So, you'll want something like `result.Alternatives[0].Transcript`. Of course, there might be more than one alternative, or the one there might have a low confidence. So, it depends on your application how you want to use it. :)

**Comment by tbpg** [comment]
I'm going to close this for now, but let us know if you have any other issues!

**Comment by DennisFaucher** [comment]
@tbpg Thank you.
