### ISSUE TITLE
getting-started/bookshelf: oauth fails with gorilla securecookie max length

### ISSUE THREAD

**Issue by talee** [GoogleCloudPlatform/golang-samples#137]
Getting an error with the bookshelf app after accepting oauth scopes from login link:

```
could not save session: securecookie: the value is too long
```

Guessing it's coming from: https://github.com/gorilla/securecookie/blob/master/securecookie.go#L288

Occurring with deployed app. Any way I can debug this?

**Comment by broady** [comment]
It's probably because the OAuth token is now too long and taking up too much space in the cookie.

The OAuth token should probably be moved to a different session.

https://github.com/GoogleCloudPlatform/golang-samples/blob/master/getting-started/bookshelf/app/auth.go#L163-L177

**Comment by talee** [comment]
@broady Got it. I ended up storing the profile in a separate CookieStore. Measuring the cookies sizes, interestingly enough the default cookie with token became 519B and the profile cookie with plus.Person type saved became 3779B.

On a separate topic, it does feels a little strange to be storing such large cookies on the client.

**Comment by talee** [comment]
Actually after switching out plus.Person with a basic struct, the profile cookie size became 1247B. I guess plus.Person simply doesn't encode efficiently.
