### ISSUE TITLE
speech: Does Google Speech API Suppress "Filler" Words?

### ISSUE THREAD

**Issue by DennisFaucher** [GoogleCloudPlatform/golang-samples#1373]
I have written a speech coach by modifying lvecaption.go. If someone says the filler word "Um" I am flagging that word in the transcription using the Go ReplaceAll function. The problem is, no matter how many times I say "Um" Google seems to suppress that word from the transcription. Is there an option in the APY not to suppress filler words? TIA.

**Comment by tbpg** [comment]
I don't think the Speech API includes filler words like "um." Perhaps there is an option, but I looked briefly (I'm not an expert on the Speech API) and didn't see one.

You may have better luck asking this type of question on StackOverflow. This repo is for Go samples embedded on cloud.google.com, so it's not the best place for general API questions.
