### ISSUE TITLE
Show IAM context with examples

### ISSUE THREAD

**Issue by kaihendry** [GoogleCloudPlatform/golang-samples#1422]
I'm struggling to figure out how to show the function's identity or permission context.

For example, how do I confirm that my function is running under PROJECT_ID@appspot.gserviceaccount.com?

Ultimately I am debugging why I don't have `Error 403: Required 'compute.instances.get' permission for 'projects/..', forbidden"`

**Comment by codyoss** [comment]
You can tell the service account the function is using either via the Cloud Console -> Cloud Functions -> Function -> Edit.

Or you can use gcloud: `gcloud functions describe MY_FUNCTION_NAME`

**Comment by kaihendry** [comment]
Sorry,  in the context of the function I was keen to learn what my permissions was. Could you point me to applicable Go API call please?

**Comment by codyoss** [comment]
Sorry for the slow response getting back to you. If I understand correctly you would like to know what roles you can use from within the function itself? Here is a small example about how to print your current iam roles.

```go
import (
	"context"
	"log"

	"google.golang.org/api/iam/v1"
)

type PubSubMessage struct {
	Data []byte `json:"data"`
}

func Example(ctx context.Context, m PubSubMessage) error {
	svc, err := iam.NewService(context.Background())
	if err != nil {
		return err
	}
	resp, err := svc.Roles.List().Do()
	if err != nil {
		return err
	}
	for _, v := range resp.Roles {
		log.Printf("role: %q\n", v.Name)
	}
	return nil
}
```

**Comment by codyoss** [comment]
Closing do to lack of response. Please feel free to re-open if you are still having issues.

**Comment by kaihendry** [comment]
Bit bewildered with the sheer amount of roles. Thank you nonetheless.
