### ISSUE TITLE
Flexible vm CloudSQL setup

### ISSUE THREAD

**Issue by atishpatel** [GoogleCloudPlatform/golang-samples#143]
I'm setting up an Go App Engine flexible environment that can connect to Second Gen Cloud SQL instance. 

The method provided in this repo requires authorizations for 0.0.0.0/0 so it's really insecure. 

There is suppose to be another method: https://cloud.google.com/sql/docs/app-engine-connect#gaev2-csqlv2 
However, it leads to an `unknown network cloudsql` or if the cloudsql dialer is added `cloudsql: not supported in App Engine "flexible environment"` error. (here is the reason for the second error https://github.com/golang/appengine/blob/master/cloudsql/cloudsql_vm.go)

Is the document on the cloud.google.com page suppose to work? If so, could the example in this repo be updated to show how to do this? 

@broady

**Comment by broady** [comment]
You're right. Thanks for the report. I noticed this today, as well. I couldn't get it to work, either.

**Comment by broady** [comment]
Instructions updated: https://cloud.google.com/appengine/docs/flexible/go/using-cloud-sql
