### ISSUE TITLE
[Cloud Tasks] Exception calling application: 'POST' has type str, but expected one of: int, long

### ISSUE THREAD

**Issue by ernsheong** [GoogleCloudPlatform/golang-samples#1431]
I tried the Go example found at https://cloud.google.com/tasks/docs/creating-http-target-tasks#creating_http_target_tasks (Cloud Tasks task creation)

But I keep getting this error:
```
rpc error: code = Unknown desc = Exception calling application: 'POST' has type str, but expected one of: int, long
```

I tried updating all the dependencies but nothing fixes this. Any idea?

**Comment by codyoss** [comment]
It looks like you are sending the string "Post" for `HttpMethod`. The backing value is actually numeric. You can use: `taskspb.HttpMethod_POST`.

**Comment by ernsheong** [comment]
My bad, finally see more context in the stacktrace today, the error was coming from an (unofficial) emulator. Cheers
