### ISSUE TITLE
[process] commit title guidelines

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/golang-samples#1511]
I've noticed a few commits recently that don't follow the style guide (`package: description of change`)

https://github.com/GoogleCloudPlatform/golang-samples/commit/b38f4a5a7e04170a3d1b60543f3419f784c7e633

It's probably about time to add a GitHub action that checks.

Does the PR title itself also need to be checked, in the case of multiple commits that'll get squashed?

Also, squashed messages are frequently low quality, but GitHub doesn't give the opportunity to check them with a bot before submitting.

We could only allow submission by the automerge bot? I think the PR body is used as the commit body?

Sorry this isn't very concrete, I'm hoping others will have some ideas. Maybe the solution is to remove this from the style guide?

/cc @tbpg

**Comment by tbpg** [comment]
Looks like we're moving toward conventional commits.

cc @codyoss

**Comment by codyoss** [comment]
The node repos have a status check for conventional commits: https://github.com/googleapis/nodejs-storage/pull/1216/checks?check_run_id=800853820. (I have not looked into it yet)

**Comment by tbpg** [comment]
Status check for conventional commits is active and being followed.
