### ISSUE TITLE
Restricted API Key and gRPC

### ISSUE THREAD

**Issue by skomski** [GoogleCloudPlatform/golang-samples#1587]
I want to use an restricted api key over grpc that works only with specific referers to access the text-to-speech api. An unrestricted key works fine with x-goog-api-key but x-origin or x-referer or referer doesnt work for the restricted key. It always returns empty referer. Not supported? Thanks for your help!

**Comment by tbpg** [comment]
Hi there. Thanks for filing an issue. But, this repo is for Go samples embedded on cloud.google.com. If you have a general question, StackOverflow or Cloud Support would be a better fit for these types of questions. StackOverflow also has the benefit of being discover-able by other users. Unfortunately, I'm not sure what the answer is to your question.
