### ISSUE TITLE
functions: HTTP Google Cloud Functions in Go results in error

### ISSUE THREAD

**Issue by qmilangowin** [GoogleCloudPlatform/golang-samples#1627]
The example for HTTP Google Cloud Functions in Go, namely on page: https://codelabs.developers.google.com/codelabs/cloud-functions-go-http/#3
doesn't successfully deploy the needed image. Endpoint will result in error: Error reading file: open gophercolor.png: no such file or directory

**Comment by qmilangowin** [comment]
Seems I was using go113 runtime instead of go111. Not sure why it doesn't work with latest runtime.

**Comment by qmilangowin** [comment]
Seems I was using go113 runtime instead of go111. Not sure why it doesn't work with latest runtime. Works with go111 runtime.
Would be good to update instructions to latest runtime

**Comment by tbpg** [comment]
Thank you for reporting this! It's definitely a bug and caused by the fact the working directory is not the same between the runtime versions (sorry!). I'll send a PR to make reading the file work locally, with go111, and with go113.

cc @grant @grayside @juliehockett
