### ISSUE TITLE
Unable to create access token using service account

### ISSUE THREAD

**Issue by abhayJava** [GoogleCloudPlatform/golang-samples#1640]
Unable to get token through implicit, explicit way as mentioned in https://github.com/GoogleCloudPlatform/golang-samples/blob/master/auth/snippets.go

Implicit way with path set as **export GOOGLE_APPLICATION_CREDENTIALS=/Users/xxx/Downloads/servicekey.json**

 dialing: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: open /Users/xxx/Downloads/servicekey.json: operation not permitted
exit status 1

package main

import (
	"context"
	"fmt"
	"log"

	"cloud.google.com/go/storage"
	cloudkms "google.golang.org/api/cloudkms/v1"
	"google.golang.org/api/iterator"
	"google.golang.org/api/option"

)
func main() {
	fmt.Println("Hello World")
	implicit()
	//explicit("/Users/xxx/Downloads/servicekey.json","xxx")
}
func implicit() {
	ctx := context.Background()

	// For API packages whose import path is starting with "cloud.google.com/go",
	// such as cloud.google.com/go/storage in this case, if there are no credentials
	// provided, the client library will look for credentials in the environment.
	storageClient, err := storage.NewClient(ctx)
	if err != nil {
		log.Fatal(err)
	}

	it := storageClient.Buckets(ctx, "project-id")
	for {
		bucketAttrs, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(bucketAttrs.Name)
	}

	// For packages whose import path is starting with "google.golang.org/api",
	// such as google.golang.org/api/cloudkms/v1, use NewService to create the client.
	kmsService, err := cloudkms.NewService(ctx)
	if err != nil {
		log.Fatal(err)
	}

	_ = kmsService

}

func explicit(jsonPath, projectID string) {
	ctx := context.Background()
	client, err := storage.NewClient(ctx, option.WithCredentialsFile(jsonPath))
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("Buckets:")
	it := client.Buckets(ctx, projectID)
	for {
		battrs, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(battrs.Name)
	}
}

**Comment by tbpg** [comment]
Are you able to do anything with those credentials? The error looks like the file couldn't be opened, so I'm wondering if this is an issue with creating an access token or an issue using that particular service account file.

**Comment by tbpg** [comment]
Closing this as it's been 7 days. But, feel free to comment if you're still having issues and we can take a look.
