### ISSUE TITLE
eventarc: use event library struct

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/golang-samples#1645]
In the Cloud Run Events Pub/Sub sample, we want to use the struct provided by the event library, not an inlined struct:

## Code
https://github.com/GoogleCloudPlatform/golang-samples/blob/292e8c9e4b0dd6c34805431d1a894c2bc751dd7f/run/events_pubsub/main.go#L28-L35

## Event type library
https://github.com/googleapis/google-cloudevents-go/blob/c543fb3cb993d15758f84f43a07e03a9ff62e718/src/google/events/cloud/pubsub/v1/data.pb.go#L42-L54

---

I'm not sure if there are more steps needed to be able to import this file.

My Go knowledge for understanding modules is lacking. Can you give me any tips for next steps needed (if any) for using `google-cloudevents-go` @grayside @tbpg?

**Comment by grant** [comment]
The sample is here now:

https://github.com/GoogleCloudPlatform/golang-samples/tree/master/eventarc/pubsub

The event type is here now:

https://github.com/googleapis/google-cloudevents-go/blob/d7141e1f03c0bb45b9c2606553aca380dd23f2ae/cloud/pubsub/v1/MessagePublishedData.go

Assigning to @michaelawyu who is working on this language.

**Comment by grant** [comment]
Pinging @michaelawyu, can you look into this issue? Ping me if there are questions.

**Comment by grayside** [comment]
To be clear, the suggestion here is that we update the non-Eventarc Cloud Run + Pub/Sub sample to use the event type library? Is the Pub/Sub payload identical between Pub/Sub and Eventarc?

**Comment by grant** [comment]
> To be clear, the suggestion here is that we update the non-Eventarc Cloud Run + Pub/Sub sample to use the event type library? Is the Pub/Sub payload identical between Pub/Sub and Eventarc?

Happy to clarify.

The GitHub issue was create on August 12, 2020 – which is significant because at the time, the API was part of Cloud Run and the product was called "Cloud Run Events".

Now the product is called "Eventarc", and there are separate APIs and samples. I've changed the title respectively.

> To be clear, the suggestion here is that we update the non-Eventarc Cloud Run + Pub/Sub sample to use the event type library?

FR is for Eventarc to use the events library for the eventarc sample. I added the sample to the README at one point:

https://github.com/googleapis/google-cloudevents-go#example-usage

>  Is the Pub/Sub payload identical between Pub/Sub and Eventarc?

Yes – the HTTP body is the same – for technical reasons, although Eventarc is a layer/service built on Pub/Sub, so we shouldn't rely on the interface being the same. I.e. we shouldn't change Pub/Sub samples (or other event source service samples).

**Comment by iennae** [comment]
Grant, 

Please take a look at this issue.

**Comment by grant** [comment]
> Grant,
> 
> Please take a look at this issue.

Yup, I know this issue.

We can add the library to the samples.

**Comment by grant** [comment]
Created a PR to fix this issue.

**Comment by grant** [comment]
Removing myself from issues as I change teams. Again, #2049 would fix this issue.
