### ISSUE TITLE
healthcare: write test for hl7v2_message_list.go

### ISSUE THREAD

**Issue by noerog** [GoogleCloudPlatform/golang-samples#1659]
Add test for https://github.com/GoogleCloudPlatform/golang-samples/blob/master/healthcare/hl7v2_message_list.go.

**Comment by tbpg** [comment]
Hey @noerog, any updates on this issue?

**Comment by noerog** [comment]
Not yet, I will add it to my next block of work and try to get it done within 2 weeks.

**Comment by tbpg** [comment]
Thanks!
