### ISSUE TITLE
functions: create facility to deploy Cloud Functions for e2e testing

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/golang-samples#1690]
In order to enable end-to-end/integration tests of Cloud Functions (#1381) we need a facility such as [cloudrunci](https://github.com/GoogleCloudPlatform/golang-samples/tree/master/internal/cloudrunci).

I propose creating `functest` as a similar internal package. However, where cloudrunci tries to enforce more of a workflow on what operations can be done, and provide facilities with various options for deployment, I think we should keep this simpler. In implementation of tests, the same pattern used in Cloud Run should be followed for Cloud Functions (#1674).

In scope here:
* Create a functest package with tests/docs
* Set up functions/testing with a first test implementation to demonstrate usage.

Not in scope:
* Retrofit all Cloud Functions E2E tests to use this new facility.

**Comment by grayside** [comment]
After discussing in #1691, our conclusion was to wrap gcloud setup & teardown in a custom TestMain for each function.

**Comment by grayside** [comment]
The intention of this approach was to create something lean. Here's what I've encountered so far:

* The first end-to-end test in the file starts at line 92.
* The GCF deployment doesn't like depending on internal packages outside the immediate directory. Specifically this is because I'm using a replace directive because I added a function to testutil:
	```
	Running "go list -m"
	go: github.com/GoogleCloudPlatform/golang-samples@v0.0.0-20201001054139-515536355696: parsing /go.mod: open /go.mod: no such file or directory
	```

Going to pause this on a design discussion.

**Comment by tbpg** [comment]
Note: any test dependencies show up in the go.mod, which means users pick them up if they deploy the function. Let's avoid the golang-samples dependency for any Cloud Functions. Tests can be in another directory, though.

**Comment by grayside** [comment]
This was for the use of github.com/GoogleCloudPlatform/golang-samples/internal/testutil. I thought we used that ubiquitously?

Putting together a short design doc to sync up on this.

**Comment by tbpg** [comment]
We haven't used it when it would lead to golang-samples in the go.mod for a Cloud Functions sample. At least not intentionally. :stuck_out_tongue:
