### ISSUE TITLE
Inappropriate resource

### ISSUE THREAD

**Issue by Developer9009** [GoogleCloudPlatform/golang-samples#1697]
hi folks

there's uri in your [readme](https://github.com/GoogleCloudPlatform/golang-samples/blob/master/storage/gcsupload/README.md) file which leads to a photo of a guy with a beer stored on a personal account. Looking weird and looking like a hidden try of a spam as orijtech appears to be a company. Should be changed probably to a thing more neutral, Storage logo or smth.

**Comment by tbpg** [comment]
Thank you for the report! We'll get it removed.
