### ISSUE TITLE
storage: missing samples

### ISSUE THREAD

**Issue by AlisskaPie** [GoogleCloudPlatform/golang-samples#1707]
In [Storage Sample Coverage](https://docs.google.com/spreadsheets/d/1EfdvfkTG0hIYAdFI_Xs3ikqfH9oyFsfKy_5gv5baURo/edit?ts=5e1e6870#gid=2137817657) following samples are missing or have wrong region tag:
- [x] storage_bucket_delete_default_kms_key
- [x] storage_generate_encryption_key 
- [x] storage_view_bucket_iam_members
- [x] storage_add_bucket_label
- [x] storage_compose_file
- [x] storage_remove_bucket_label
- [x] storage_change_file_storage_class
- [x] storage_enable_versioning
- [ ] storage_set_metadata
- [x] storage_set_bucket_public_iam
- [x] storage_define_bucket_website_configuration
- [x] storage_download_public_file
- [x] storage_get_service_account
- [x] storage_cors_configuration
- [x] storage_disable_versioning
- [x] storage_copy_file_archived_generation
- [x] storage_object_csek_to_cmek
- [ ] storage_change_default_storage_class
- [x] storage_delete_file_archived_generation
- [x] storage_remove_cors_configuration

**Comment by tbpg** [comment]
@tritone @crwilcox What is the next step for this issue?

**Comment by tritone** [comment]
Reassigning to @JesseLovelace who is working on sample completeness. Jesse, is there any remaining work to be completed here or should this be closed out?
