### ISSUE TITLE
Pub/Sub: samples audit and cleanup

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/golang-samples#1734]
Please rename:
- `pubsub_publish_with_error_handling_that_scales` to `pubsub_publish_with_error_handler`

Please remove:
- the region tag `pubsub_publish` but keep the region tag `pubsub_quickstart_publisher` and the sample.

Please add: 
- `pubsub_subscriber_async_pull_custom_attributes` ([docs](https://cloud.google.com/pubsub/docs/pull#pull-messages-with-custom-attributes))
- `pubsub_publisher_retry_settings`

**Comment by hongalex** [comment]
Regarding the `pubsub_publisher_retry_settings` sample, the Go client does not support custom retry settings. This is [noted in the docs](https://cloud.google.com/pubsub/docs/publisher#retry):

> not all client libraries support custom retry settings; see the API Reference documentation for your chosen language
