### ISSUE TITLE
docs: CONTRIBUTING guide feedback

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/golang-samples#1735]
In reviewing the current state of the CONTRIBUTING.md, I see a few issues. Opening this here for discussion prior to sending PRs.

1. The guide refers to snippets and quickstarts. Neither of these apply to samples of hosting products. Should "platform products" or "sample apps" be a clearly delineated third category?

2. Many PRs that update go.mod go versions have feedback on not raising the go version. We should capture this in a "go module maintenance" section. Suggestion: `The go.mod specifies the minimum version of Go needed to run the code that we are using in tests.`

Ex: #1733

3. Insufficient disambiguation for test resources: guide suggesting to prefix resource names with the projectID. This seems insufficient to avoid name collisions even with the gimmeproj system. Maybe [PROJECT]-[SAMPLE]-[RESOURCE], but that likely exceeds length limitations for at least some resource names.

Ex. https://github.com/GoogleCloudPlatform/golang-samples/blob/master/CONTRIBUTING.md#creating-resources-for-tests

**Comment by tbpg** [comment]
1. Sure. If there are things specific to those we want to be consistent about, let's go for it.
1. Yes. I don't know about specific wording. The section title should be something like "Don't update Go versions in go.mod files" then we can give a caveat of when to do it in the body.
1. Yes. But, we don't need to standardize? Anything after the project ID is up to the test writer.
