### ISSUE TITLE
all: garbage collect GCP resources used in tests

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/golang-samples#174]
We create GCP resources such as Storage buckets and Pub/Sub topics to run the integration tests. These resources should be deleted if tests fail to clean them.

Build an internal package to generate timestamped resource names and provide a function to garbage collect existing resources if they have been around more than one day.

We can run collection in the beginning of every test or separately once every night once we have scheduled builds.

**Comment by jba** [comment]
Maybe we should generalize/make visible https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/logging/internal/testing/unique.go.

**Comment by rakyll** [comment]
We need a very similar solution what unique.go does for generating names.

Our current naming format also includes a repo prefix.

```
"golang-samples-repo-" + prefix +  "-" +  timestamp
// e.g. golang-samples-repo-buckets-<timestamp>
```

**Comment by broady** [comment]
We don't exactly need anything that complex because the tests are sharded
across multiple projects. Aggressive clean up by prefix or name is fine.

**Comment by broady** [comment]
Likely superseded by #220. Other tests are fine, but may leave behind some garbage.

Maybe best to move to creating resources that always have the same name for a given test project.

If anyone wants to work on this, (@rakyll?) then the first thing would be to do an audit of existing resources created for each test.

**Comment by tbpg** [comment]
This is mostly done on samples I've seen. So, I'm going to close it. As we rewrite samples to follow the style guide, we can make sure that resources are cleaned up. But, I don't think we need to proactively go through all samples and delete.
