### ISSUE TITLE
spanner: remove CLIs from getting started guide (delete snippet.go)

### ISSUE THREAD

**Issue by hengfengli** [GoogleCloudPlatform/golang-samples#1763]
Two tasks included: 
- Remove CLIs in the getting started guide
- Remove `snippet.go`

**Comment by tbpg** [comment]
@hengfengli, any updates on finishing up this cleanup? Searching, I only see one reference to snippet.go: https://cloud.google.com/community/tutorials/cloud-spanner-commit-timestamp-change-log (there is also what appears to be a duplicate of that file).

cc @jsimonweb

**Comment by hengfengli** [comment]
This seems to be paused at the moment.
