### ISSUE TITLE
firestore: update documentation and sample uses Set instead of Update

### ISSUE THREAD

**Issue by StefMa** [GoogleCloudPlatform/golang-samples#1808]
Hey guys 👋 

I noticed that the documentation (and therefore this samples) for `updating` a document are wrong.
[The documentation](https://firebase.google.com/docs/firestore/manage-data/add-data#update-data) says this:
![Screenshot 2020-10-30 at 09 22 34](https://user-images.githubusercontent.com/10229883/97676783-732f6c80-1a91-11eb-9b2b-6b9a0069b845.png)

But I think it should use the [`DocumentRef.Update`](https://pkg.go.dev/cloud.google.com/go/firestore#DocumentRef.Update) function instead. Like in all the other language samples.

Or is it intended to use [`DocumentRef.Set`](https://pkg.go.dev/cloud.google.com/go/firestore#DocumentRef.Set) over `DocumentRef.Update` for some reasons? 🤔

**Comment by codyoss** [comment]
@StefMa Thank you for pointing this out! I believe the two should yield the same result as long as the merge option is used. But I think we should be using the Update method as you have pointed out to be consistent with the docs and other samples.
