### ISSUE TITLE
How to add `scheduleTime` when creating a Cloud Task programmatically?

### ISSUE THREAD

**Issue by tiagomelo** [GoogleCloudPlatform/golang-samples#1822]
Hi,

[Here](https://cloud.google.com/tasks/docs/comp-tasks-sched#key_differences) we see that `scheduleTime` can be used to determine when a given cloud task will run. But [this example](https://cloud.google.com/appengine/docs/standard/go111/taskqueue/push/example) does not show how to do it. 

Could you please point out how to set it? 

Thanks!

**Comment by tiagomelo** [comment]
Actually it's just a matter of setting `ETA`:

```
t := taskqueue.NewPOSTTask("/_ah/queue/test", params)
   	
now := time.Now().UTC()
scheduleDateTime := now.Add(time.Duration(2) * time.Minute)

t.ETA = scheduleDateTime
```

👍

**Comment by tbpg** [comment]
Glad you got it figured out! Random comment, no need for the `time.Duration` conversion. You can do `2 * time.Minute` and it works. Here's an example: https://play.golang.org/p/ZROGzyMeqDn.

**Comment by tiagomelo** [comment]
cool! Thanks for the tip! :)
