### ISSUE TITLE
Wrong Condition

### ISSUE THREAD

**Issue by SoulAndris** [GoogleCloudPlatform/golang-samples#1831]
https://github.com/GoogleCloudPlatform/golang-samples/blob/42b670ab6b56db4a821d62fd37ebd1c52e7baab2/storage/objects/objects_test.go#L113

I am of course new to Go and am learning Google API, but shouldn't there be the following condition?
`if got, want := buf.String(), object1;` **_!strings_**`.Contains(got, want)`

**Comment by SoulAndris** [comment]
Sorry, I figured it out, everything is correct there))

**Comment by tbpg** [comment]
Glad you got it figured out! Let us know if you run into any other issues.
