### ISSUE TITLE
functions: CI/CD example 

### ISSUE THREAD

**Issue by ddobrijalowski** [GoogleCloudPlatform/golang-samples#1848]
[The example for cloud functions CI/CD](https://github.com/GoogleCloudPlatform/golang-samples/blob/a12e2fd198c022aa062c6897713347e1816f737d/functions/ci_cd/cloudbuild.yaml#L17) doesn't feel right. I'm just starting to learn how to use the service and golang so I might be completely wrong, but:
1. It pulls golang image directly from mirror.gcr.io. According to [mirror documentation](https://cloud.google.com/container-registry/docs/pulling-cached-images):
- _Google Cloud services such as Cloud Build and Google Kubernetes Engine automatically check for cached images before attempting to pull an image from Docker Hub._
- _Only obtain cached images on mirror.gcr.io by configuring the Docker daemon. A request to pull directly from mirror.gcr.io will fail if a cached copy of the image does not exist._
2. It will pull latest (currently 1.15.5) golang image. Cloud functions support 1.11.6 and 1.13.8 runtimes ([docs](https://cloud.google.com/functions/docs/concepts/go-runtime#execution_environment)) using custom Ubuntu 18.04 based images.

There are a few options for making it better:
1. Just change the image to golang:1.13.8 (example uses go113 runtime) and pull it from docker hub (using the mirror transparently).
2. Extend the example by creating a custom Ubuntu based image with golang 1.13.8. This adds complexity, especially if we don't want to rebuild it on every CI trigger, but it's a step closer to production environment than official debian based images from docker hub.
3. This would be a feature request, but IMO the best solution from CI best practices perspective: publish go113 and go111 runtimes that are used in the production environment (or new images synced with the production if they contain any secret sauce).

**Comment by grant** [comment]
I haven't used this file before. I'd assume a PR is welcome, or perhaps Ace is more familiar with the sample.

**Comment by ace-n** [comment]
I think @tbpg added the original version of this; I'll reassign this to him.

**Comment by ace-n** [comment]
@tbpg ping on this?

cc @grayside

**Comment by tbpg** [comment]
No updates from me -- haven't had a chance to update + test.

**Comment by ace-n** [comment]
Ping @tbpg @codyoss
