### ISSUE TITLE
logging: update quickstart sample

### ISSUE THREAD

**Issue by 0xSage** [GoogleCloudPlatform/golang-samples#1861]
Improve the Logging quickstart [sample in Golang](https://cloud.google.com/logging/docs/samples/logging-quickstart#logging_quickstart-go). Quickstart should work out of the box and contain all the instructions (in comments) so users can immediately see their logs. 

Additional criteria: 
- [ ] include comments on various [ways to authenticate ](https://cloud.google.com/docs/authentication)
- [ ] encourage users to log with [standard log wrapper](https://pkg.go.dev/cloud.google.com/go/logging#example-Logger.StandardLogger) rather than writing [LogEntries](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry). Context: In an ideal world, customers should be able to use existing logging frameworks native to their language. With some simple appender/handler to also ship logs to Cloud Logging. Customers aren't locked into logging library syntax, thus it's easier to both onboarding and offboard off of these client libraries. 
- [ ] comment that if users need more customizable logs, redirect to samples on [writing log entries](https://cloud.google.com/logging/docs/samples/logging-write-log-entry)
- [ ] if applicable, a test for this sample

**Comment by telpirion** [comment]
Closing this old feature request. Reopen if this feature is still desired.
