### ISSUE TITLE
logging: add sample for getting sink

### ISSUE THREAD

**Issue by 0xSage** [GoogleCloudPlatform/golang-samples#1863]
https://cloud.google.com/logging/docs/samples/logging-get-sink

Similar to this Nodejs sample, add a Golang sample showcasing how to retrieve Cloud Logging Sink metadata & an accompanying test.

Region tag: logging_get_sink

**Comment by telpirion** [comment]
Given the age of this issue and the lack of interest from product team, I'm going to close.
