### ISSUE TITLE
logging: improve the Write logEntry sample

### ISSUE THREAD

**Issue by 0xSage** [GoogleCloudPlatform/golang-samples#1865]
Improve the Write logEntry sample on [this page](https://cloud.google.com/logging/docs/samples/logging-write-log-entry)

This page is referenced by [docs](https://cloud.google.com/logging/docs/api/tasks/creating-logs) that explicitly talk about LogEntries. So we should demo this “advanced” logging technique, even though we do recommend the standard log wrapper approach in the quickstarts.

Criteria: 
- [ ] Demo how to write a text logEntry (textPayload)
- [ ] Demo how to write a struct logEntry (jsonPayload)
- [ ] Include: severity level, labels, resource type (“global”)
- [ ] Demo: batch logging vs writing one log at a time
- [ ] Update accompanying tests

Region tag: `logging_write_log_entry`

**Comment by telpirion** [comment]
Looking at the referenced page, it looks like the following features have been added:

+ Severity
+ Text payload
+ Struct logging

Closing as obsolete.
