### ISSUE TITLE
run: markdown preview edit window constricts text to narrow column

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/golang-samples#1924]
Expected: constraint the text comfortably to the width of the text area.

### Actual
![Screen Shot 2021-01-29 at 3 14 03 PM](https://user-images.githubusercontent.com/283489/106336905-c35ecc00-6244-11eb-8205-61cf75615ac8.png)

**Comment by tbpg** [comment]
Hey @grayside, what is the next step here?

**Comment by tbpg** [comment]
Any ideas on timeline? Working on cleaning up issues in this repo.

**Comment by grayside** [comment]
I expect this quarter.
