### ISSUE TITLE
pubsub: sample to flush Queue

### ISSUE THREAD

**Issue by MushuEE** [GoogleCloudPlatform/golang-samples#1938]
Hello, I see in the read me that new samples are not accepted. I had a use case where I wanted to flush my PubSub queue of all current messages and end. I saw that someone else was interested in this behavior. (https://github.com/googleapis/google-cloud-go/issues/881)

I was able to get a sample for this working and I think customers might find it useful 
```go
	// Handle individual messages in a goroutine.
	go func() {
		// Start timer to give up after 20s of no pubsub events
		timer := time.NewTimer(20 * time.Second)
		for {
			select {
			case <-timer.C:
				cancel()
				return
			case msg := <-cm:
				fmt.Fprintf(w, "Got message :%q\n", string(msg.Data))
				fmt.Fprintln(w, "Attributes:")
				for key, value := range msg.Attributes {
					fmt.Fprintf(w, "%s = %s", key, value)
				}
				msg.Ack()

				// reset timer since we got a PubSub Event
				if !timer.Stop() {
					<-timer.C
				}
				timer.Reset(20 * time.Second)
			}
		}
	}()
```

Curious if there is a way to add this sample at all.

**Comment by hongalex** [comment]
This approach will work sometimes, but not all the time, as the lack of messages is not indicative that all messages have been delivered. Upon discussion with other folks on the team, this is a pattern is not something we want to promote.
