### ISSUE TITLE
Spanner Array Examples

### ISSUE THREAD

**Issue by leadinglocally** [GoogleCloudPlatform/golang-samples#200]
Please make some example that includes use of arrays.

I tried 'unmarshalling' the row element type []string into *[]string and []string, but it fails with this:

type []string cannot be used for decoding ARRAY[STRING]

**Comment by leadinglocally** [comment]
Also some examples for the ToStruct method for rows would be nice.

type Provider struct {
  Name string               `spanner:"name"`
  Address string            `spanner:"address"`
  Country string            `spanner:"country"`
  Lat float64               `spanner:"lat"`
  Lng float64               `spanner:"lng"`
  Tags []string             `spanner:"tags"`
}

something like that?

**Comment by Ulexus** [comment]
For others who run into this problem, the issue appears to be that `ARRAY` types can be null, so you must use `spanner.NullString` as the receiving type for `ARRAY[STRING]` return values.

**Comment by Ulexus** [comment]
Example:

```go
type Country struct {
  Name string
  Cities []spanner.NullString
}

func load(ctx context.Context, tx *spanner.ReadOnlyTransaction, name string) (*Country,error) {
  it := tx.Query(ctx, spanner.NewStatement(`
    SELECT a.Name, ARRAY(
        SELECT b.Name FROM cities b WHERE a.Country = b.Country
     ) FROM countries a 
     WHERE 
        a.Name = 'USA'
   `))
   defer it.Stop()

   row, err := it.Next()
   if err == iterator.Done {
      return nil, errors.New("not found")
   }
   if err != nil {
      return nil, err
   }

   var country Country
   err = row.ToStruct(&country)
   return &country, err
}
```

**Comment by odeke-em** [comment]
@Ulexus thank you for the response/example. Would you like to make that into a PR that we can review and that can be your credited contribution?

**Comment by jabubake** [comment]
@jsimonweb FYI
