### ISSUE TITLE
datastore: metadata __namespace__ sample doesn't work?

### ISSUE THREAD

**Issue by adams-sarah** [GoogleCloudPlatform/golang-samples#204]
This one doesn't work for me:
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/datastore/snippets/snippet_test.go#L641-L663

```
query := datastore.NewQuery("__namespace__").
		Filter("__key__ >=", startNamespace).
		Filter("__key__ <", endNamespace).
		KeysOnly()
```

I see:
client.GetAll: rpc error: code = InvalidArgument desc = __key__ filter value must be a Key
exit status 1

Looking at the ruby/gql examples, maybe it should be something like
```
.Filter("__key__ >=", datastore.NameKey("__namespace__", startNamespace, nil)
```

but I really have no idea.

@broady @rakyll

**Comment by jabubake** [comment]
@ryanmats FYI
