### ISSUE TITLE
Question(storage): delete one record from MD

### ISSUE THREAD

**Issue by gebv** [GoogleCloudPlatform/golang-samples#2066]
To delete one record from MD need execute two opers (remove all MD and sets interested MD items)? It is ok? 

- step 1 - create object with MD (two items) but **without data!**
- step 2 - get object - got all MD
- step 3 - upd MD - delete one item from MD
- step 4 - get object - got all MD, but I want one item from MD (because step 3 deleted one item)

```golang
        c := mustCSClient()
	b, _ := c.Bucket(bucketName)

	// step 1
	fw := b.Object(fileName).NewWriter(context.Background())
	// NOTE: if sets data then metadata is not writed
	// fw.Write([]byte("foobar"))
	fw.Metadata = map[string]string{"a": "b", "c": "d"}
	err := fw.Close()
	assert.NoError(t, err)

	// step 2
	obj := b.Object(fileName)
	attrs, err := obj.Attrs(context.Background())
	assert.NoError(t, err)
	t.Logf("Step 2: %v", attrs.Metadata)

	// step 3
	delete(attrs.Metadata, "c")
	t.Logf("Step 3: %v", attrs.Metadata)
	_, err = obj.Update(context.TODO(), gcStorage.ObjectAttrsToUpdate{
		Metadata: attrs.Metadata,
	})
	assert.NoError(t, err)

	// step 4
	obj = b.Object(fileName)
	attrs, err = obj.Attrs(context.Background())
	assert.NoError(t, err)
	t.Logf("Step 4: %v", attrs.Metadata)
```

PS If create an object with data, then MD will not be written? It is ok?

UPD: cloud.google.com/go/storage v1.15.0

**Comment by frankyn** [comment]
Hi @gebv,

Thanks for the issue. I don't think we currently support deleting a metadata key from an object per https://github.com/googleapis/google-cloud-go/issues/380#issuecomment-250321401. 

I'll reach out to @tritone when he's back in the office to double check, but this looks like a gap in implementation.

**Comment by gebv** [comment]
@frankyn thx for answer. I don't think MD item with an empty value makes any sense. And I expected should overwritten MD - all items and not try to merged (server side).

**Comment by frankyn** [comment]
Hi @gebv,

I synced with @tritone and this is a gap in our support and I'm looking into a way to potentially support this but not certain if it will be the right approach.

As a workaround you could do the following:
```
delete(attrs.Metadata, "c")
// Delete all object metadata
_, err = obj.Update(context.TODO(), gcStorage.ObjectAttrsToUpdate{
	Metadata: nil,
})

// re-Insert remaining metadata without key "c"
_, err = obj.Update(context.TODO(), gcStorage.ObjectAttrsToUpdate{
	Metadata: attrs.Metadata,
})
```

Thank you for your patience.

**Comment by gebv** [comment]
Yes, with two requests I solve the problem. Thx
