### ISSUE TITLE
all: many samples don't call client.Close(), leading to memory leaks

### ISSUE THREAD

**Issue by abrender** [GoogleCloudPlatform/golang-samples#2078]
The code samples for Secret Manager have "client, err := secretmanager.NewClient(ctx)" but no corresponding "defer client.Close()"  which resulted in my application, which used the code in the samples as a template, having a memory leak.

It'd be great if the sample code could make it clear in the code or comments that .Close() should be called.

Thanks!

**Comment by tbpg** [comment]
Thank you for the report! I'll get those cleaned up.
