### ISSUE TITLE
bug: functions/security/idtoken.go

### ISSUE THREAD

**Issue by bweston92** [GoogleCloudPlatform/golang-samples#2125]
The following doesn't seem to work:

```
https://github.com/GoogleCloudPlatform/golang-samples/blob/HEAD/functions/security/idtoken.go
```

by default using a service account file with it I get the following:

```
neither scopes or audience are available for the self-signed JWT
```

I can get it to make a request but have to use `option.WithAudiences(targetURL)` in the call to `idtoken.NewClient` and it works fine.

Is this desired behaviour?
If so can improve these documents?
If not, where should I list a bug?

**Comment by codyoss** [comment]
This is being tracked on [google-api-go-client](https://github.com/googleapis/google-api-go-client/issues/1092) and has a [fix out for review](https://github.com/googleapis/google-api-go-client/pull/1096). For now please use google.golang.org/api@v0.48.0, sorry for the inconvenience.
