### ISSUE TITLE
The tutorial "Running the Go Bookshelf on Container Engine" contains references to the deprecated "aedeploy" tool

### ISSUE THREAD

**Issue by lrudolph1** [GoogleCloudPlatform/golang-samples#215]
[This tutorial](https://cloud.google.com/go/tutorials/bookshelf-on-container-engine#go_dependencies) says:

> To containerize the Go application, this tutorial uses the aedeploy tool, which assembles your app's dependencies. 

However, it looks like the aedeploy tool is deprecated: https://github.com/golang/appengine/pull/65

**Comment by broady** [comment]
I updated this tutorial this morning.

Please take another look!
