### ISSUE TITLE
Gstreamer - Connection refused - Golang

### ISSUE THREAD

**Issue by antoniomanuelnd** [GoogleCloudPlatform/golang-samples#2192]
Hi everyone,

I'm stuck for several weeks trying to use the microphone with the code of livecaption.go
I've only made two changes in the code, adding this:
```
serviceAccountJSONFile := "/home/antoniomanuel_nunez/test-speech-microphone/keyname.json"
os.Setenv("GOOGLE_APPLICATION_CREDENTIALS", serviceAccountJSONFile)
```

I've install gstreamer, build the program and then execute the next command:

```
gst-launch-1.0 -v pulsesrc ! audioconvert ! audioresample ! audio/x-raw,channels=1,rate=16000 ! filesink location=/dev/stdout | ../test-speech-microphone/test-speech-microphone
```

But I have these errors, I've been searching a lot but I have not found nothing about them:
```
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstPulseSrc:pulsesrc0: Failed to connect: Connection refused
Additional debug info:
pulsesrc.c(1015): gst_pulsesrc_open (): /GstPipeline:pipeline0/GstPulseSrc:pulsesrc0
```

I'm using this in Cloud Shell, I don't know if this could be a problem, but I think that it should works in Cloud Shell.
Did somebody has this issue? How did you resolve it?
I would appreciate any help.

Thank you!

**Comment by codyoss** [comment]
Hey sorry you have been having trouble running the sample. Have you tried running this sample locally? I am not sure it will work in Cloud Shell since I don't think that environment will have access to local devices like your microphone.

**Comment by antoniomanuelnd** [comment]
> Hey sorry you have been having trouble running the sample. Have you tried running this sample locally? I am not sure it will work in Cloud Shell since I don't think that environment will have access to local devices like your microphone.

Hi! Yes, I've tried in Ubuntu, but I have the same error. I've checked if the microphone is working and in the settings I can see that it is working...

**Comment by codyoss** [comment]
It seems like the error is coming from gstreamer and not from the sample code. I am not familiar with this piece of software so I don't think I can help too much debugging that. Have you tried to direct microphone input in any other ways? I believe there are some Go libraries for working with such things but I have not tried them myself.

**Comment by codyoss** [comment]
Closing issue do to lack of response. Please comment back if you are still having issues.
