### ISSUE TITLE
compute: samples should use accessors

### ISSUE THREAD

**Issue by vchudnov-g** [GoogleCloudPlatform/golang-samples#2248]
Instead of fetching the fields directly, we should use accessor methods like `GetName()`, `GetMachineType()`

For example, in https://github.com/GoogleCloudPlatform/golang-samples/blob/d6e572168a429e67987f6f1046856ff2041c1f24/compute/list_instances.go#L54

**Comment by codyoss** [comment]
Are we sure we want to do this just for compute? I get the argument here since it is a pointer type that needs to be dereferenced, but in general none of our samples use the generated getters. I would say most Gophers are used to working with the structs directly.

**Comment by codyoss** [comment]
An example from secretmanager for instance:

https://github.com/GoogleCloudPlatform/golang-samples/blob/d6e572168a429e67987f6f1046856ff2041c1f24/secretmanager/list_secrets.go#L46-L60

**Comment by vchudnov-g** [comment]
I think it makes sense to do it for all samples for all APIs: using the getters unless we're testing for fields presence explicitly.

**Comment by codyoss** [comment]
If we want to do it for compute I think that is fine, but for non-pointer types the getters don't provide much value imo. Like I mentioned above, I think most people are used to working with struct fields directly and that is the design pattern used by clients that have manual layers built in front of them today. (No getters or setters)

Again from secretmanager:

https://github.com/googleapis/go-genproto/blob/433400c27d0517dc71fad914d494d85afd63c067/googleapis/cloud/secretmanager/v1/resources.pb.go#L186-L191

**Comment by vchudnov-g** [comment]
I think we should at least do it for compute. For other APIs, the advantage of using getters  is that it helps train people to use them in general, so that they're more likely to use them when they do bring some value (like `optional` fields which have pointer types). 

@noahdietz , I know you have some opinions on this as well.

**Comment by rsamborski** [comment]
@FrodoTheTrue FYI

**Comment by noahdietz** [comment]
Yeah I mean we don't have to change every instance of it everywhere, the primary target is `optional` fields (which is...every field? in compute) where it is way too easy to deref a `nil` field. 

I understand that most people are probably using direct field access for non-pointers and I guess it's OK, but the "best practice" as documented by the protobuf go folks is to use the getters when possible. Not a hill I will die on here, but there is also the added benefit in using the getter for non-pointer fields in that it protects users from `nil` deref panics, see here: https://play.golang.org/p/WzS2hdgXo2L

The gettor you mentioned @codyoss handles the case where the pointer receiver is `nil` and returns `""`, whereas a direct field access panics. Unfortunately, this surface is rather confusing having both a getter and an exported field.

**Comment by codyoss** [comment]
I guess I am not worried about nil derefs, but I guess it is nice to not have to deref done for users.

> The gettor you mentioned @codyoss handles the case where the pointer receiver is nil and returns "", whereas a direct field access panics. Unfortunately, this surface is rather confusing having both a getter and an exported field.

That is true, but in practice will never happen (with this sample or similar code) because the error should be checked before referencing the value. If errors are not checked a lot of Go code would be full of panics as nil refs are generally returned in such cases 😛

**Comment by noahdietz** [comment]
> That is true, but in practice will never happen (with this sample or similar code) because the error should be checked before referencing the value

Sure, but this also applies to nested messages that are pointer fields & chaining accessors for fields. Like I said, it's a best practice thing, not "the only way." It's a good habit to get into and to share.

> I guess I am not worried about nil derefs, but I guess it is nice to not have to deref done for users.

This is very real for `optional` fields. The field might not be populated in the response. One should either check `!= nil` or use the accessor.

**Comment by codyoss** [comment]
> This is very real for optional fields. The field might not be populated in the response. One should either check != nil or use the accessor.

You are right, I take that back for optional fields. If we want to talk about the more general case some more lets add an item to the next Go biweekly. I think this has been a long patten for this repo though to directly access fields. It is too bad the generated getters arn't more idomatic (Not including the word Get)

**Comment by FrodoTheTrue** [comment]
Was done here: https://github.com/GoogleCloudPlatform/golang-samples/pull/2261
