### ISSUE TITLE
@JStr84galaxy Was there any problem in the recent version of the dependency?

### ISSUE THREAD

**Issue by JStr84galaxy** [GoogleCloudPlatform/golang-samples#2287]
@JStr84galaxy Was there any problem in the recent version of the dependency?

_Originally posted by @suztomo in https://github.com/GoogleCloudPlatform/java-docs-samples/issues/6168#issuecomment-940585523_

**Comment by codyoss** [comment]
I am not sure what this issue is about. Closing.
