### ISSUE TITLE
compute: Add line breaks for documentation

### ISSUE THREAD

**Issue by savijatv** [GoogleCloudPlatform/golang-samples#2326]
https://github.com/GoogleCloudPlatform/golang-samples/blob/eed36110a8ab28bc07bfb3e06e72302385a3e833/compute/set_usage_export_bucket.go#L28

[same comment for line no. 50]
When you include these samples in our documents, such long comments are not wrapped properly and it's not readable. Can we break such long comments in this document like this:
 // setUsageExportBucket sets the Compute Engine usage export bucket for the Cloud project.
// This sample describes how to interpret the default value for the report name prefix parameter. 

Please add a TODO comment to replace the variables following this comment, as applicable. You might want to consider moving the comment at line no. 50 before // reportNamePrefix := "", because it's better to clarify this before you set a value for this prefix.

**Comment by codyoss** [comment]
I agree with the lines could be broken down a bit. I am not sure I understand what you are saying about TODOs, can you elaborate or give an example of what you mean?

**Comment by FrodoTheTrue** [comment]
PR: https://github.com/GoogleCloudPlatform/golang-samples/pull/2330

**Comment by FrodoTheTrue** [comment]
As we discussed together with Savija, we don't use "uncomment variables" way in Golang samples (like in Node.js for example): https://github.com/googleapis/nodejs-compute/blob/main/samples/createInstance.js#L45).
