### ISSUE TITLE
Add READMEs for speech

### ISSUE THREAD

**Issue by danaharon** [GoogleCloudPlatform/golang-samples#235]
1) Readme should contain instructions that explain how to get the sample to compile and how to run it.
2) Readme should include the "go get -u cloud.google.com/go/speech/apiv1" command so that users will know that they need to run it

**Comment by odeke-em** [comment]
@danaharon would you like to submit a PR for this? Your issue description makes for great requirements for a PR, IMHO.

**Comment by danicat** [comment]
Seems like nobody is working on this right now... it's ok if I do it?

**Comment by adams-sarah** [comment]
yas! that would be wonderful, thank you @danicat

**Comment by adams-sarah** [comment]
@danicat, can't seem to assign you. but this is yours if you want it :)

**Comment by danicat** [comment]
@adams-sarah probably only collaborators can be assigned, but let me handle this. I'm doing some cleaning up in the examples for all the machine learning APIs. I've used some of them in one of my presentations last week so I want to do this while it's fresh. :)

**Comment by broady** [comment]
thanks, @danicat 

Check out other language repos, too.

https://github.com/GoogleCloudPlatform/python-docs-samples
https://github.com/GoogleCloudPlatform/nodejs-docs-samples

**Comment by danicat** [comment]
Hey @broady, I had a look at the other repos... it seems that every repo has it's own way of organizing stuff, even though the content should be pretty much the same. I wonder if it wouldn't be possible to set a standard for everybody to follow, at least regarding the documentation and repo structure.

**Comment by danicat** [comment]
May we close this one? Or there's anything else that needs to be done?

**Comment by broady** [comment]
Seems done to me. If there are any improvements, someone can open a new issue.
