### ISSUE TITLE
appengine_flexible helloworld: cant `gcloud app deploy`

### ISSUE THREAD

**Issue by yuvalk** [GoogleCloudPlatform/golang-samples#2367]
ERROR: (gcloud.app.deploy) Required file is not uploaded: [app.yaml]. This file should not be added to an ignore list (https://cloud.google.com/sdk/gcloud/reference/topic/gcloudignore)

didnt change anything..

**Comment by codyoss** [comment]
I am unable to reproduce this behavior. If you look in the directory of the sample you will find an `app.yaml`. Running `gcloud app deploy` from that directory should work. Can you elaborate on the issue you are facing? https://github.com/GoogleCloudPlatform/golang-samples/tree/main/appengine_flexible/helloworld

**Comment by yuvalk** [comment]
I'm running off fedora 35
all I did was
1. clone the repo
2. cd into the appengine_flexible/hellowowlrd directory
3. execute `gcloud app deploy`

and Ive got the above error.

after copying that directory aside (say to `/tmp/helloworld`) it works fine

*BTW: to make gcloud cli work on fedora at all, I had to set `CLOUDSDK_PYTHON=/usr/bin/python3.6` otherwise Ive got errors because my python=/usr/bin/python3.10

**Comment by codyoss** [comment]
This sounds like it may be an issue with your environment and gcloud in that case. Would you mind opening an issue [here](https://issuetracker.google.com/issues/new?component=187143) with details you have provided me. That is the issue tracker for glcloud. I will close out this issue for now as I don't believe this is an issue with the sample itself. Thanks for the report!
