### ISSUE TITLE
bigquery: insert sample

### ISSUE THREAD

**Issue by Mistic92** [GoogleCloudPlatform/golang-samples#2382]
Hi, is there any sample with bigquery insert struct? I can't find any.

**Comment by shollyman** [comment]
Is https://github.com/GoogleCloudPlatform/golang-samples/blob/main/bigquery/snippets/table/bigquery_table_insert_rows.go what you're looking for?  It uses an Inserter with a struct.

**Comment by shollyman** [comment]
Closing this due to lack of further response.  If I've misunderstood, please revisit the issue with more details.
