### ISSUE TITLE
Add gcloud tests to prevent regressions

### ISSUE THREAD

**Issue by shreejad** [GoogleCloudPlatform/golang-samples#2389]
gcloud 367.0.1 adds the Go modules functionality for App Engine Flex.

Golang's default behavior is to build an app the Go modules way if go.mod is present in any parent directory. In previous gcloud versions, even though go.mod was present in the root directory, gcloud ignored the file and build the app the GOPATH way. After gcloud 367.0.1, gcloud app deploy starts using the Go modules way to build the app. As GAE requires go.mod to be in the same directory as app.yaml, `gcloud app deploy` **fails** (go.mod is in the root directory while app.yaml is in a child sub-directory).

Suggestion: We should add gcloud tests (as part of PR presubmits maybe?) to prevent further regressions.

**Comment by codyoss** [comment]
I think we can update any samples that need to be, but I am not sure we should outright test gcloud here. I believe we always install the latest gcloud in our tests. If we need to re-build base containers to make sure there is a new enough version we can do that.

**Comment by splace** [comment]
gcp  basic tutorial broken because of this. testing anyone?

**Comment by telpirion** [comment]
Given the age of this issue and lack of sufficient details, I'm going to close. Please re-open with additional details if this issue arises again.
