### ISSUE TITLE
scheduler: example for sending pubsub message

### ISSUE THREAD

**Issue by StevenACoffman** [GoogleCloudPlatform/golang-samples#2410]
Hello,

I would like to use the cloud scheduler API to send a pubsub message. The godoc documentation does not contain an example, so I would like there to be a sample here. I know I can do this via the CLI:

```gcloud beta scheduler jobs create pubsub <JOB> --schedule "0 9 1 * *" --topic <TOPIC> --message-body "test" --attributes key1=value1,key2,value2```

But I am unclear as to how to accomplish this in Go using the API:
https://pkg.go.dev/google.golang.org/api/cloudscheduler/v1#pkg-functions

**Comment by codyoss** [comment]
I can try to throw together a working example in a few, but I would like to nudge you towards our newer client lib: https://pkg.go.dev/cloud.google.com/go/scheduler@v1.0.0/apiv1#CloudSchedulerClient.CreateJob

**Comment by codyoss** [comment]
```golang
package main

import (
	"context"
	"log"

	scheduler "cloud.google.com/go/scheduler/apiv1"
	schedulerpb "google.golang.org/genproto/googleapis/cloud/scheduler/v1"
)

func main() {
	ctx := context.Background()
	client, err := scheduler.NewCloudSchedulerClient(ctx)
	if err != nil {
		log.Fatalf("unable to create client: %v", err)
	}
	defer client.Close()

	job, err := client.CreateJob(ctx, &schedulerpb.CreateJobRequest{
		Parent: "projects/PROJECT-ID/locations/REGION",
		Job: &schedulerpb.Job{
			Schedule: "0 9 1 * *",
			Target: &schedulerpb.Job_PubsubTarget{
				PubsubTarget: &schedulerpb.PubsubTarget{
					TopicName: "projects/PROJECT-ID/topics/TOPIC-NAME",
					Data:      []byte("test"),
					Attributes: map[string]string{
						"key1": "value1",
					},
				},
			},
		},
	})
	if err != nil {
		log.Fatalf("unable to create job: %v", err)
	}
	log.Print("Job Name: %v", job.Name)
}

```

Does the following work for you?

**Comment by StevenACoffman** [comment]
That is perfect! Thank you very much!

**Comment by mmcelwain01** [comment]
I think we could charge for for both your help and my research and the cloud. The cloud fees looking back are around $10,000 google a month I do believe. Not  including GitHub time and my fee and time. This includes most of the world. What do you all think .. keeping into consideration Google cloud needs to profit too. I have not received any money from this adventure and it was just me  until 2020.  It is very interesting and important to us all. It could pay my bills and then sum...my friend who is building another app with me just found out he need a kidney he currently is at 17%> life justs keeps getting in our way to move forward very fast. I was a single parent when we met and decided to build an app to help us all then life kept changing just like the internet.  Just in case any one is interested in my personal self. All my children are grown but could always use a hand out. They don't know what I have been up to on the worldwide web. Someday they will learn. Smile and hugs to you all. This is so wonderful 😊

**Comment by mmcelwain01** [comment]
Did me making any changes effect the gamers on Twitter or other platforms? If so, I really want to allow any coders and gamers. I just feel this is something good for them to do.

**Comment by mmcelwain01** [comment]
We can add them to a fork or create a fork for them. With a special meta tag.

**Comment by mmcelwain01** [comment]
Maybe the Google go app. Yeah

**Comment by mmcelwain01** [comment]
And Mozilla Firefox

**Comment by StevenACoffman** [comment]
Just out of curiosity, but were the last few comments added by a program or a person? They make no sense to me.

**Comment by mmcelwain01** [comment]
Yes, my apologies if you don't understand I can explain,  if you have any
questions about them. I hope.

Michelle C McElwain

**Comment by codyoss** [comment]
@mmcelwain01 Please keep issues on topic.

**Comment by codyoss** [comment]
Closing this issue as it looks like the sample proved useful for @StevenACoffman . I will see if we can eventually get a real sample up on cloud.google.com for this API. But for now the code in this issue should work.
