### ISSUE TITLE
endpoints/grpc: add client sample using JWT auth tokens

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/golang-samples#242]

**Comment by odeke-em** [comment]
@broady perhaps this PR https://github.com/GoogleCloudPlatform/golang-samples/pull/189 already addresses that?

**Comment by broady** [comment]
Not exactly. That one adds Google ID, and is for HTTP/1.

We need something similar to the existing JWT example, but for gRPC.

We currently only have API key auth for gRPC:
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/endpoints/getting-started-grpc/client/main.go

**Comment by tbpg** [comment]
Declaring bankruptcy on this - it's been >2 years. Will track separately if we decide we need another sample here.
