### ISSUE TITLE
Typo error in HTTP Google Cloud Functions in Go lab

### ISSUE THREAD

**Issue by sarkarbikram90** [GoogleCloudPlatform/golang-samples#2500]
In this lab the step **Change to the directory containing the code for this codelab:** 

"cd golang-samples-**master**/functions/codelabs/gopher" 

it should be "cd golang-samples-**main**/functions/codelabs/gopher"

![typo](https://user-images.githubusercontent.com/54825429/161730017-a61f047a-1bdb-457f-b938-d10a5fc1b5a2.JPG)

**Comment by codyoss** [comment]
Hey @sarkarbikram90 I think that there is likely a different spot this issue should be opened, but I am not sure where that is. Can you please share the link to think content so I can help direct this feedback, thanks

**Comment by codyoss** [comment]
Closing this issue as have not heard back.
