### ISSUE TITLE
run/grpc-server-streaming: why not need to open HTTP/2 

### ISSUE THREAD

**Issue by ZoeShaw101** [GoogleCloudPlatform/golang-samples#2506]
By test ,I found  HTTP/2.0 should be opened in following case of Cloud Run gRPC invoke
- grpc bidirectional streaming
- gprc client streaming 

While grpc server streaming seems not need to open HTTP/2.0, but I don't know why?

**Comment by muncus** [comment]
Hi there!
Can you share more about the tests you performed?

My understanding is that all GRPC Servers **must** support HTTP/2.0 ( which is supported by [this comment](https://github.com/grpc/grpc-go/blob/728364accfb93cd52003fb38a6412c8e4965116b/internal/transport/handler_server.go#L49-L51) in the underlying library.)

The HTTP server can support both HTTP 1.x and HTTP 2.0, but the GRPC framework enforces the protocol restriction for incoming GRPC requests in the function linked above.

**Comment by muncus** [comment]
Hello again!

Without more information here, there's not much we can do. I'm going to close this issue for now, but feel free to reopen with some information about the tests you performed, and i'll be happy to continue looking into this.
