### ISSUE TITLE
Set delete protection default to true

### ISSUE THREAD

**Issue by rsamborski** [GoogleCloudPlatform/golang-samples#2537]
The sample shows how to use delete protection, but by default the [flag is set to false](https://github.com/GoogleCloudPlatform/golang-samples/blob/23c3e737eb0aed7bf5f9511107ea7e8ee0ee1c79/compute/instances/preventing-accidental-vm-deletion/create_instance.go#L33). In NodeJS and Java we set this flag to true, so I suggest to the same in this case.

**Comment by FrodoTheTrue** [comment]
PR: https://github.com/GoogleCloudPlatform/golang-samples/pull/2541
