### ISSUE TITLE
Weird error message

### ISSUE THREAD

**Issue by timograf** [GoogleCloudPlatform/golang-samples#2637]
Hello

Looks like you got a copy/paste error all over the file, since you are not calling "bigtable.NewAdminClient" but "bigtable.NewClient".

https://github.com/GoogleCloudPlatform/golang-samples/blob/ba5aa117abd4ccd77864dc66e7d142e6e03098db/bigtable/reads/reads.go#L40

**Comment by codyoss** [comment]
Thank you for the thoughtful feedback!
