### ISSUE TITLE
appengine: NewContext passed an unknown http.Request

### ISSUE THREAD

**Issue by warent** [GoogleCloudPlatform/golang-samples#264]
If I download and run the appengine_flexible/helloworld app, everything is fine.

If I make the tiniest adjustment and add `appengine.NewContext(r)` right above `fmt.Fprint(w, "Hello world!")` then I get a huge panic that results in `appengine: NewContext passed an unknown http.Request`

Is there something about this that's fundamentally wrong? Please help me, this has been absolutely bedeviling me.

**Comment by broady** [comment]
appengine.NewContext isn't necessary for App Engine flexible.

I suggest using: `r.Context()` instead. This gives you a context scoped to the request. That is, it's cancelled if the client goes away or the connection drops.

Use `context.Background()` for anything else.

**Comment by warent** [comment]
You're the real MVP. Many thanks

**Comment by dchenk** [comment]
I get the error `appengine: NewContext passed an unknown http.Request` and the app crashes when I pass in a new `*http.Request` into `log.Errorf` (where `log` is from the package `google.golang.org/appengine/log`.

In some functions, the request variable isn't available, so when I want to log something with the `appengine/log.log` function the entire app fails. This even happens in production (not just on the local server).

Please help fix this soon! And thanks in advance.

**Comment by adams-sarah** [comment]
@dchenk can you paste some code?

specifically, your import paths (the relevant ones at least), your call to `log.Errorf` and the relevant lines around it.

**Comment by adams-sarah** [comment]
@dchenk the issue you're describing was just reported here https://github.com/golang/appengine/issues/85
We'll track this issue there.
Thanks for your report.

**Comment by arulrajalivi** [comment]
I am seeing the issue while trying to get appengine context for using memcache as memcache requires appengine context.

appengine: NewContext passed an unknown http.Request

**Comment by adams-sarah** [comment]
@arulrajalivi this issue is closed. see golang/appengine#85 for details.
