### ISSUE TITLE
Remove `w, `

### ISSUE THREAD

**Issue by KazuakiM** [GoogleCloudPlatform/golang-samples#2647]
https://github.com/GoogleCloudPlatform/golang-samples/blob/a9c8603f3a8d007af2f7d0258fa9777254f421b3/storage/objects/download_file.go#L62

**Comment by enocom** [comment]
Thanks for the issue, but this is actually perfectly correct.

See https://pkg.go.dev/fmt#Fprintf.

**Comment by KazuakiM** [comment]
Thank you !
