### ISSUE TITLE
Add example for cloud-iot as well

### ISSUE THREAD

**Issue by anirudh-chhangani** [GoogleCloudPlatform/golang-samples#267]
The cloud iot beta has examples for python node and java. Examples for golang are also needed thanks.

**Comment by odeke-em** [comment]
Do we have an API client generated for the cloudiot beta in Go? Nor do I see any public docs for python, node or Java. @anirudh-chhangani if possible would you mind providing a link to those docs?

For Go, I don't see one looking at the directory listings at:
- https://godoc.org/cloud.google.com/go
- https://godoc.org/google.golang.org/api

**Comment by anirudh-chhangani** [comment]
You will have to sign up for cloud-iot beta, those docs aren't public yet.

**Comment by take-cheeze** [comment]
I've wrote my own samples connecting to GCP Cloud IoT Core using MQTT:
https://github.com/fusic/gcp-iot-core-golang-sample/blob/master/main.go
I hope this may help somebody.

**Comment by DazWilkin** [comment]
+1 to this request

I'm a Googler in Cloud albeit not in IoT (just interested) and wrote a sample too (having only belatedly discovered @take-cheeze code -- nice!)... I'm "enlivening" the discussion internally too.
https://gist.github.com/DazWilkin/d45e7b62468419c9929afd77751377cf

Blogged about the solution I'm trying to develop using Cloud IoT with Onion Omega devices:
https://medium.com/google-cloud/google-cloud-iot-core-golang-b130f65951ba

**Comment by tbpg** [comment]
We now have IoT samples at https://github.com/GoogleCloudPlatform/golang-samples/tree/master/iot, which are embedded in pages like [this](https://cloud.google.com/iot/docs/how-tos/devices).
