### ISSUE TITLE
Cloud Logging: No Cloud Run Jobs environment detection

### ISSUE THREAD

**Issue by guillaumeblaquiere** [GoogleCloudPlatform/golang-samples#2751]
#### Environment details

  - OS type and version: Cloud Run Jobs
  - Go version: 1.15 and 1.17
  - `google-cloud-logging` version: 1.4.2

#### Steps to reproduce

  1. Use this code for a working example in Cloud Run
Main.go
```
package main

import (
	"context"
	"log"
	"cloud.google.com/go/logging"
)

var logger *log.Logger

func main() {
	ctx := context.Background()

	// Sets your Google Cloud Platform project ID.
	projectID := "gdglyon-cloudrun"

	// Creates a client.
	client, err := logging.NewClient(ctx, projectID)
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}
	defer client.Close()

	// Sets the name of the log to write to.
	logName := "my-log"

	logger = client.Logger(logName).StandardLogger(logging.Warning)

	// Logs "hello world", log entry is visible at
	// Cloud Logs.
	logWarning()
}

func logWarning() {
	logger.Println("hello world")
}
```
go.mod
```
module golang.com/gblaquiere

go 1.15

require cloud.google.com/go/logging v1.4.2
```
Dockerfile
```
FROM golang:1.17 AS builder

# Set necessary environmet variables needed for our image
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# Move to working directory /build
WORKDIR /build

# Copy and download dependency using go mod
COPY go.mod .
COPY go.sum .
RUN go mod download

# Copy the code into the container
COPY . .

# Build the application
RUN go build -o main .

FROM debian:buster-slim
RUN set -x && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /build/main /

ENTRYPOINT ["/main"]
```

Deploy on cloud run. It failed (no webserver deployed) but the warning trace is present in the Cloud Run logs section with that `label` part

```
resource: {
labels: {
configuration_name: "log-format-go"
location: "us-central1"
project_id: "gdglyon-cloudrun"
revision_name: "log-format-go-00003-tuj"
service_name: "log-format-go"
}
type: "cloud_run_revision"
}
severity: "WARNING"
```
--------
Now, do the same thing with Cloud Run Jobs
Same container, same code

This time the logs are present but not visible in the Cloud Run Jobs logs section. Why? Because the label is not correct:

```
resource: {
labels: {
project_id: "gdglyon-cloudrun"
}
type: "project"
}
severity: "WARNING"
```

The Cloud Logging Library doesn't correctly detect the Cloud Run Jobs runtime environment and don't put the correct values in the logs that cause a filtering issue in the Cloud Run Jobs UI.

(Cloud Run team is aware of that issue)

Note: same issue in Python library: https://github.com/googleapis/python-logging/issues/663

**Comment by codyoss** [comment]
@guillaumeblaquiere Thanks for the report, would you mind opening this issue over here: https://github.com/googleapis/google-cloud-go/issues. It will get more traction from the team. Thanks!

**Comment by ace-n** [comment]
Hi everyone,

@guillaumeblaquiere thanks again for this issue.

I've [made a copy of this issue](https://github.com/googleapis/google-cloud-go/issues/7150) in the `google-cloud-go` repository; please feel free to add more comments there.

Thanks!
