### ISSUE TITLE
Model ID is invalid. It should start with 3 letters

### ISSUE THREAD

**Issue by TawsifKarim** [GoogleCloudPlatform/golang-samples#2762]
I have trained and deployed a model for image classification (multi-label). When I try to use 
the following code, I get an error =>` rpc error: code = InvalidArgument desc = Model ID is invalid. It should start with 3 letters."`
But in the dashboard If i go to the console.cloud.google.com > vertex ai > model registry and then select version details Tab, The Model_ID does not have any 3 letter prefix in it. Its a plain 18 digit number. Dont know what to do here. Help required.

```
client, err := automl.NewPredictionClient(ctx)

....

req := &automlpb.PredictRequest{
		Name: fmt.Sprintf("projects/%s/locations/%s/models/%s", "MY_PROJECT_ID", "LOCATION", "MODEL_ID"), //<= where can I get this Model's Prefix
		Payload: &automlpb.ExamplePayload{
			Payload: &automlpb.ExamplePayload_Image{
				Image: &automlpb.Image{
					Data: &automlpb.Image_ImageBytes{
						ImageBytes: bytes,
					},
				},
			},
		},
		// Params is additional domain-specific parameters.
		Params: map[string]string{
			// score_threshold is used to filter the result.
			"score_threshold": "0.1",
		},
	}

	resp, err := client.Predict(ctx, req)
	if err != nil {
		 return fmt.Errorf("Predict: %v", err)
	}
```

**Comment by codyoss** [comment]
Hey @TawsifKarim this repo is used for some sample code and is not a great place for general API questions. For that I recommend reaching out to one of the links on the [API's support page](https://cloud.google.com/vision/automl/getting-support) or one of the specific api [issue trackers](https://cloud.google.com/support/docs/issue-trackers). Hope that helps point you in the right direction.
