### ISSUE TITLE
firestore: firestoreClient.Batch is deprecated

### ISSUE THREAD

**Issue by cnovak** [GoogleCloudPlatform/golang-samples#2804]
Sample code and reference docs have an example of batch deleting a collection using `firestoreClient.Batch` which is deprecated.

## References
- Documentation: https://firebase.google.com/docs/firestore/manage-data/delete-data#collections
- Sample Code: https://github.com/GoogleCloudPlatform/golang-samples/blob/9187374b211af561d1e4e329e843aaa7e31d8222/firestore/save.go#L282

**Comment by telpirion** [comment]
Good catch! Ideally we would use `firestoreClient.Bulkwriter` for this operation.
