### ISSUE TITLE
dlp: Missing README 

### ISSUE THREAD

**Issue by kumudaPriya98** [GoogleCloudPlatform/golang-samples#3005]
Currently golang-samples/dlp/ does not have a README.

Please include the information:
1.  steps for samples setup 
2.  examples on how to run the code samples

Thanks!

**Comment by meredithslota** [comment]
Most samples folders don't have their own README — I spot-checked a few random ones and couldn't find any that _did_. I wonder if it would be more helpful to add something to the main README that would apply to all samples?

**Comment by telpirion** [comment]
I agree @meredithslota -- I don't think that there's a hard requirement for a README in this folder. Closing the issue.
