### ISSUE TITLE
Organize examples by category

### ISSUE THREAD

**Issue by danicat** [GoogleCloudPlatform/golang-samples#309]
We currently have a big table with all examples for all GCP tools in the same place. I'm suggesting organizing the examples by category so they would be easier to browse.

Suggested categories: 
- Management
- Compute
- Storage
- Networking
- Big Data
- Machine Learning

Please see:
https://www.slideshare.net/DanielaPetruzalek/google-cloud-platform-um-portal-para-a-era-do-machine-learning/21?src=clipshare

**Comment by broady** [comment]
+1 for this in a README, but -1 for it in the directory structure.

**Comment by danicat** [comment]
I agree. I am proposing only changing the table at the `Index` section on the main README.md.

**Comment by broady** [comment]
Oh, yeah! I missed the "big table" part :)

**Comment by tbpg** [comment]
Thank you, @danicat!
