### ISSUE TITLE
Provide comment & justification for using `skipKOKORO()` function 

### ISSUE THREAD

**Issue by telpirion** [GoogleCloudPlatform/golang-samples#3234]
Kokoro is the CI/CD system used to ensure that all samples going into this repo operate as intended. We should not circumvent the tests run by Kokoro.

(I apparently missed that this function was being added in #3191 .)

https://github.com/GoogleCloudPlatform/golang-samples/blame/8d3766ae3e94270000e2753fe89e33d5b8f1d16b/dlp/snippets/metadata/metadata_test.go#L73

**Comment by AarshD-crest** [comment]
Following the language team's recommendation and after a discussion with @annadata, I've gone ahead and removed the skipKOKORO() function from all the existing DLP-related code as outlined in the referenced pull request (PR - https://github.com/GoogleCloudPlatform/golang-samples/pull/3250). As a result, we can now proceed to close this issue.

**Comment by annadata** [comment]
The issue has been addressed in #3250
