### ISSUE TITLE
dlp/risk: `setupPubSub()` function needs to be duplicated across samples

### ISSUE THREAD

**Issue by telpirion** [GoogleCloudPlatform/golang-samples#3281]
Several of the DLP samples call a `setupPubSub()` function that is defined in a [different file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/dlp/snippets/risk/risk.go#L25). Having samples invoke a function not included in the imported libraries OR in the sample leads to customer confusion.

This function needs to be duplicated in each of the samples that calls it.

**Comment by telpirion** [comment]
Another option could be to add a comment that explains where to find the `setupPubSub()` function. However, that could make the documentation experience a little more complicated.

**Comment by annadata** [comment]
@telpirion Thanks for pointing this out. We will look into it.
