### ISSUE TITLE
topic.EnableMessageOrdering undefined (type *"cloud.google.com/go/pubsub".Topic has no field or method EnableMessageOrdering)

### ISSUE THREAD

**Issue by f0o** [GoogleCloudPlatform/golang-samples#3286]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**The issue you're having must be related to a file in this repository.** We are unable to provide assistance for issues unrelated to samples in this repository.

Please include as much information as possible:

## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/golang-samples/blob/HEAD/pubsub/topics/publish_ordering.go#L47

## Did you change the file? If so, how?
```
	topic := client.Topic("somestringhere")
	topic.EnableMessageOrdering = true
```

## Describe the issue

```
# command-line-arguments
./main.go:55:8: topic.EnableMessageOrdering undefined (type *"cloud.google.com/go/pubsub".Topic has no field or method EnableMessageOrdering)
```

Using

```
	cloud.google.com/go/pubsub v1.3.1
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by f0o** [comment]
Following on this I also get:

```
./main.go:119:4: unknown field OrderingKey in struct literal of type "cloud.google.com/go/pubsub".Message
```

godocs show both exist

**Comment by muncus** [comment]
The version you report using ( ` cloud.google.com/go/pubsub v1.3.1`) is a couple years old.
The latest version (1.33.0) does have these fields.

It looks like the fields you are looking for were added in 1.4.0, but i'd still recommend using the latest available version.
