### ISSUE TITLE
bigtable: provide a README for the search example

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/golang-samples#344]
A Cloud Bigtable engineer suggested that the [Cloud Bigtable search example](https://github.com/GoogleCloudPlatform/golang-samples/tree/master/bigtable/search) could use a README. Ideally the README would cover all of the following information:

+ Prerequisites (e.g., creating the table `shakespearetemplate`)
+ Running the example
+ Command-line options
+ What port the server is listening on

Originally filed as GoogleCloudPlatform/google-cloud-go#252, before the search example moved to this repo.

**Comment by tbpg** [comment]
We're moving away from having in depth readme instructions in the samples repo. We should link to the cloud.google.com docs.

Side note: we also shouldn't have command line tools if they aren't used in samples. Samples should be tested with unit tests.

Closing this for now.
