### ISSUE TITLE
datastore - ExampleTransaction_getOrCreate

### ISSUE THREAD

**Issue by Regner** [GoogleCloudPlatform/golang-samples#355]
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/datastore/snippets/snippet_test.go#L612

The linked example is supposed to check if an entity exists, and if it does not exist create it. It doesn't seem to actually verify if the entity exists between the get and create.

**Comment by broady** [comment]
That happens with the `err != datastore.ErrNoSuchEntity` check.
