### ISSUE TITLE
ServeHttp method gets called twice when running outyet server

### ISSUE THREAD

**Issue by anant2614** [GoogleCloudPlatform/golang-samples#400]
The outyet project example requires to run the continuous polling server locally.After running the server,when I make a request through browser,the serveHttp method gets called twice.Can someone please explain why this is so?

**Comment by tbpg** [comment]
Sorry for the slow response. I'm not familiar with the outyet project and didn't find any references to it in this repo. It's possible the second request is from the browser for a favicon? Closing this for now, but feel free to respond with a link to the problematic code.
