### ISSUE TITLE
appengine samples: should we specify env?

### ISSUE THREAD

**Issue by campionfellin** [GoogleCloudPlatform/golang-samples#419]
Should we explicitly specify the standard environment for App Engine in the `app.yaml` files in the appengine/ examples? 

For example, in https://github.com/GoogleCloudPlatform/golang-samples/blob/master/appengine/helloworld/app.yaml

Should we add: `env: standard` to line 3? This would match the examples in the Flex Environment in appengine_flexible/ where it specifies `env: flex`.

**Comment by broady** [comment]
No, standard is the default.

**Comment by campionfellin** [comment]
👍
