### ISSUE TITLE
influx to bigQuery

### ISSUE THREAD

**Issue by gesaleh** [GoogleCloudPlatform/golang-samples#423]
in the example i don't see a migration from other DB 
I would like to migrate time series collections from influxdb to bigquery

**Comment by tbpg** [comment]
Thank you for the report. You're correct, we don't have a specific guide for migrating from InfluxDB to BigQuery (or another database). But, we do have a few guides for how to represent, import, and analyze time series data with GCP:

* This article references financial data, but might be helpful in general: https://cloud.google.com/solutions/time-series/bigquery-financial-forex.
* This article describes *BigTable* time series schema design: https://cloud.google.com/bigtable/docs/schema-design-time-series.

If you do end up finding a good solution, it might be a good candidate for a [community tutorial](https://cloud.google.com/community/) (where you can also find a link to [request a tutorial](https://github.com/GoogleCloudPlatform/community/issues?q=is%3Aopen+is%3Aissue+label%3A%22tutorial+request%22)).
