### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by brotherhod** [GoogleCloudPlatform/golang-samples#426]
Missing package:
github.com/broady/preprocess/lib/preprocess
Which is a dependency of the package
GoogleCloudPlatform/golang-samples/internal/testutil (specifically the generated.go file)
Work around would be to 'go get' the package but should a prototype be part of the master code base?  

Perhaps including the preprocess library in the main code base?

**Comment by broady** [comment]
This is only a test dependency: if non-test code depends on that package,
it's not good.

**Comment by brotherhod** [comment]
I've run a search on testutil and preprocess and neither appear in non-test code.  I'll go get the package so I can run the tests.  A bit of a risk though as the compiler won't error when non-test has this dependency (although it shouldn't in practice).

**Comment by brotherhod** [comment]
If the risk is to be accepted should there be a line or two mentioning this on the CONTRIBUTING.md ?  Happy to add something now if you think it wise.

**Comment by tbpg** [comment]
To run the tests, you'll need to run `go get` with the `-t` option. From `go help get`:
> The -t flag instructs get to also download the packages required to build
> the tests for the specified packages.

It would be great to mention this in CONTRIBUTING.go. Related to #389.
