### ISSUE TITLE
CI lint broken

### ISSUE THREAD

**Issue by BigBlackWolf** [GoogleCloudPlatform/golang-samples#4372]
## In which file did you encounter the issue?
[.github/workflows/go.yaml](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/workflows/go.yaml#L40)

## Did you change the file? If so, how?
No

## Describe the issue

Yesterday was released v0.25.0 update for [tools package](https://pkg.go.dev/golang.org/x/tools?tab=versions). It requires go 1.22, however the samples repo currently leverage go1.21 and because of that [CI pipeline is broken](https://github.com/GoogleCloudPlatform/golang-samples/actions/runs/10788456928/job/29920175082?pr=4371). Please take a look.

Thanks!

**Comment by telpirion** [comment]
On it!
