### ISSUE TITLE
spanner: snippet tests are flaky

### ISSUE THREAD

**Issue by tbpg** [GoogleCloudPlatform/golang-samples#551]
We should add the project name to the database name. Relying on timestamps to be unique can cause data races. See https://github.com/GoogleCloudPlatform/golang-samples/blob/master/spanner/spanner_snippets/snippet_test.go#L29

```
snippet_test.go:44: run("addnewcolumn", "projects/golang-samples-tests/instances/golang-samples-tests/databases/test-1533489027"): rpc error: code = FailedPrecondition desc = Duplicate column name Albums.MarketingBudget.
snippet_test.go:44: run("addstoringindex", "projects/golang-samples-tests/instances/golang-samples-tests/databases/test-1533489027"): rpc error: code = FailedPrecondition desc = Duplicate name in schema: AlbumsByAlbumTitle2.
snippet_test.go:44: run("createtabledocswithhistorytable", "projects/golang-samples-tests/instances/golang-samples-tests/databases/test-1533489027"): rpc error: code = FailedPrecondition desc = Duplicate name in schema: Documents.
```

**Comment by cpanato** [comment]
i will take this one as first contrib

**Comment by tbpg** [comment]
Thank you! It might be difficult to test without a Spanner instance, but tests will run when you create the PR. Let me know if you have any questions. :)

[Here](https://github.com/GoogleCloudPlatform/golang-samples/blob/master/storage/buckets/main_test.go#L44) is an example of using `testutil.SystemTest` to get the `ProjectID` and use it in a bucket name.
