### ISSUE TITLE
stackdriver logging sample issue

### ISSUE THREAD

**Issue by Dipen-Dedania** [GoogleCloudPlatform/golang-samples#568]
I'm trying to follow GO sample doc from - https://cloud.google.com/logging/docs/reference/libraries

I have created Serviceaccount key and trying to use that file (using env variable and also tried with code) but I'm not able to see any logs in https://console.cloud.google.com/logs/viewer

I tried directly with powershell and I can see that log in viewer.
`gcloud logging write my-test-log "Hey stack driver"`

Here's my code,

```
package main

import (
	"log"
	// Imports the Stackdriver Logging client package.
	"cloud.google.com/go/logging"
	"golang.org/x/net/context"
	"fmt"
	"encoding/json"
)

func main() {
	ctx := context.Background()

	// Sets your Google Cloud Platform project ID.
	projectID := "d-XXXXX"

	// Creates a client.
	//client, err := logging.NewClient(ctx, projectID, option.WithCredentialsFile("servicekey.json"))
	client, err := logging.NewClient(ctx, projectID)
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}

	// Sets the name of the log to write to.
	logName := "my-test-log"

	// Selects the log to write to.
	logger := client.Logger(logName)

	// Sets the data to log.
	text := "Hello, world!"

	// Adds an entry to the log buffer.
	logger.Log(logging.Entry{Payload: text})

	j := []byte(`{"Name": "Bob", "Count": 3}`)
	logger.Log(logging.Entry{Payload: json.RawMessage(j)})

	// Closes the client and flushes the buffer to the Stackdriver Logging
	// service.
	if err := client.Close(); err != nil {
		log.Fatalf("Failed to close client: %v", err)
	}

	fmt.Printf("Logged: %v\n", text)
}
```

Not sure what's wrong. Thanks in advance.

**Comment by Dipen-Dedania** [comment]
I was looking into wrong section (aka service account) but it's visible only in Google Project.
<img width="423" alt="dropdown" src="https://user-images.githubusercontent.com/5135662/44203811-ff357200-a16d-11e8-8bae-e8a1f37fd121.PNG">

**Comment by tbpg** [comment]
Thanks for filing this with a reproducible issue and including your fix! That's awesome!

Is there something we should update to make this more clear?
