### ISSUE TITLE
vision: sample generation template needs a GCS-only and local-only options

### ISSUE THREAD

**Issue by alixhami** [GoogleCloudPlatform/golang-samples#569]
The sample here: https://github.com/GoogleCloudPlatform/golang-samples/blob/057d899bf97d4ea75c883da4b410fc1699090188/vision/detect/generated/sample-template.go#L340

is only for GCS, but a local sample was also generated (with the same code). Please add the ability to specify GCS or Local only samples to the template.

@davidcavazos mentioned that it was not possible to fix this by creating another non-generated file within the same directory.

**Comment by broady** [comment]
This API method only works with GCS, not on a local file?

**Comment by alixhami** [comment]
Yes, it's GCS only.

**Comment by tbpg** [comment]
Generation was removed in #782.

**Comment by alixhami** [comment]
In this case, the `vision_text_detection_pdf` sample should be deleted.
