### ISSUE TITLE
Package context available in the standard library as of Go 1.7

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/golang-samples#575]
Shall we make a sweep update for package context in all the subdirectories? Replacing `golang.org/x/net/context` with `context`. 

"As of Go 1.7 this package is available in the standard library under the name context. " (Source: [godoc](https://godoc.org/context))

Go 1.7 was released in Aug 2016.

**Comment by broady** [comment]
Very soon. November 2018 is when 1.6 is turned down for GAE.

We probably could do this now, since 1.9 is GA on GAE.

**Comment by tbpg** [comment]
We should probably wait a bit longer before dropping 1.6. November is a couple months away.

**Comment by tbpg** [comment]
Fixed by #601.
