### ISSUE TITLE
Bookshelf - deploy to appengine fails

### ISSUE THREAD

**Issue by vicgrad** [GoogleCloudPlatform/golang-samples#590]
Hi, 

Following the bookshelf tutorial, when I run 
  `gcloud app deploy`
I get:
```
main-package: github.com/GoogleCloudPlatform/golang-samples/getting-started/bookshelf/app
2018/08/29 17:13:35 failed analyzing /Users/zzz/go/src/github.com/GoogleCloudPlatform/golang-samples/getting-started/bookshelf/app: cannot find package "golang.org/x/sys/unix" in any of:
        ($GOROOT not set)
        /Users/zzz/go/src/golang.org/x/sys/unix (from $GOPATH)
GOPATH: /Users/zzz/go
```

GOROOT is actually set to /usr/local/go

**Comment by vicgrad** [comment]
Never mind:
go get golang.org/x/sys/unix

Maybe the tutorial could use a section about getting the dependencies

**Comment by tbpg** [comment]
Thanks for the report. Hopefully this is covered in step 5 of https://cloud.google.com/go/getting-started/tutorial-app? I ran `go get github.com...` in a clean environment and it downloaded the `golang.org/x/sys/unix` package.
