### ISSUE TITLE
container_registry: tests are flaky

### ISSUE THREAD

**Issue by tbpg** [GoogleCloudPlatform/golang-samples#603]
https://github.com/GoogleCloudPlatform/golang-samples/pull/589/files#diff-7cb53750e1548a1fe7e691a3bec1ce59R284

```
samples_test.go:295: invalid occurrence count: 5; want: 3
```

This has happened a few times in the last week.

**Comment by tbpg** [comment]
Happened again. Bumping priority to p0, or we can `t.Skip` the test for now.

**Comment by DanSanche** [comment]
I have a potential fix staged here: https://github.com/GoogleCloudPlatform/golang-samples/pull/605 

It's working so far, but I haven't encountered the error case yet, so it's hard to say for sure. I'll force test runs a few more times throughout the day to be safe.
