### ISSUE TITLE
iap: write samples

### ISSUE THREAD

**Issue by tonglil** [GoogleCloudPlatform/golang-samples#606]
It would be great if you can provide samples for IAP (as you've done with Python and PHP).

https://cloud.google.com/iap/docs/authentication-howto#iap_make_request-php
https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/iap

**Comment by tbpg** [comment]
Thank you for reporting this! We are tracking the missing samples internally, but haven't had a chance to add them for Go.

**Comment by tbpg** [comment]
We're unfortunately in the same state. I'm going to close this issue as we have a duplicate internally.

Thank you, again, for reporting this.

**Comment by tonglil** [comment]
Is it because the go libraries don't allow for this?

**Comment by tbpg** [comment]
It's definitely possible to do with Go. I'm not sure what the _best_ way to do it is off the top of my head, though.
