### ISSUE TITLE
Documentation/example request: Speech API non-blocking long-running process

### ISSUE THREAD

**Issue by johnfrombluff** [GoogleCloudPlatform/golang-samples#633]
The existing example code uses the longrunning function Wait(), which blocks the main program for several minutes. Could someone update the example code showing how to display a progress report to the user, so they don't think the program has crashed! 

Thanks for your great work,

John

**Comment by tbpg** [comment]
Thanks! You can see the docs for the [long running operation in GoDoc](https://godoc.org/cloud.google.com/go/speech/apiv1#LongRunningRecognizeOperation). In particular, you can use `Poll`, `Metadata`, and `Done`. These don't give a progress indicator, but you could run this in a loop and give some feedback to the user indicating it's still processing (or run wait in a goroutine and send a notification on a channel when it finishes).

We won't be adding a dedicated sample for this, so I'm going to close the bug (all samples should be embedded somewhere in the docs). But, let me know if you have trouble with the above suggestions.

Thank you for filing a bug!
