### ISSUE TITLE
Alternative way to set credentials for GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by Gelembjuk** [GoogleCloudPlatform/golang-samples#655]
I have golang app that uses google vision API and google video intelligence API.
To set credentials i set the ENV variable GOOGLE_APPLICATION_CREDENTIALS . I set a file path here where my credentials are stored.

But i want to make this to work differently. My credentials are not in a file but are in a string variable inside my app.
For now i store that value to temp file and than set it to GOOGLE_APPLICATION_CREDENTIALS .
But i don't like this way. Is it possible to set API credentials for cloud.google.com/go/vision/apiv1 without this file?

**Comment by tbpg** [comment]
You can use [`option.WithCredentialsJSON`](https://godoc.org/google.golang.org/api/option#WithCredentialsJSON) to pass a `[]byte` with the JSON for your service account.

You're probably aware of this, but there are some docs about how to set up authentication (including best practices) [here](https://cloud.google.com/docs/authentication/production#auth-cloud-implicit-go). In particular, be sure to **never store your credentials in the source of your application**, including during development and testing.

I'm going to close this bug, but feel free to respond with additional detail. You can also ask on and link to a StackOverflow question, which might be more discover-able.

**Comment by Gelembjuk** [comment]
> You can use [`option.WithCredentialsJSON`](https://godoc.org/google.golang.org/api/option#WithCredentialsJSON) to pass a `[]byte` with the JSON for your service account.
> 
> You're probably aware of this, but there are some docs about how to set up authentication (including best practices) [here](https://cloud.google.com/docs/authentication/production#auth-cloud-implicit-go). In particular, be sure to **never store your credentials in the source of your application**, including during development and testing.
> 
> I'm going to close this bug, but feel free to respond with additional detail. You can also ask on and link to a StackOverflow question, which might be more discover-able.

Can you provide an example of how to use this with Google Vision?
For example, i have the code
```
func detectLabels(w io.Writer, file string, credentialsFilePath string) error {
        os.Setenv("GOOGLE_APPLICATION_CREDENTIALS", credentialsFilePath)
        ctx := context.Background()

        client, err := vision.NewImageAnnotatorClient(ctx)
        if err != nil {
                return err
        }
        f, err := os.Open(file)
        if err != nil {
                return err
        }
        defer f.Close()
        image, err := vision.NewImageFromReader(f)
        if err != nil {
                return err
        }
        annotations, err := client.DetectLabels(ctx, image, nil, 10)
        if err != nil {
                return err
        }

        if len(annotations) == 0 {
                fmt.Fprintln(w, "No labels found.")
        } else {
                fmt.Fprintln(w, "Labels:")
                for _, annotation := range annotations {
                        fmt.Fprintln(w, annotation.Description)
                }
        }
        return nil
}
```

What to change here to use a credentials from a variable? How to use  option.WithCredentialsJSON and where to set it here?

**Comment by tbpg** [comment]
You got it. You can also pass the path to a file, as in https://cloud.google.com/docs/authentication/production#auth-cloud-explicit-go.
