### ISSUE TITLE
datastore: queries with namespace names 

### ISSUE THREAD

**Issue by balanatarajan** [GoogleCloudPlatform/golang-samples#656]
I am unable to find examples which has namespace names in queries. I can help with examples. My developers got a bit confused without an example

**Comment by tbpg** [comment]
Thanks for the feedback, @balanatarajan! Which product is this for? Are there any pages in particular where you expected to see this example?

**Comment by balanatarajan** [comment]
Thanks for getting back so quickly @tbpg . This is specifically for cloud data store. I would like to see them in this https://cloud.google.com/datastore/docs/concepts/queries page

**Comment by balanatarajan** [comment]
These snippets https://github.com/GoogleCloudPlatform/golang-samples/blob/master/datastore/snippets/snippet_test.go don't have an example too

**Comment by tbpg** [comment]
Got it. I'll make a note internally. We'd have to write docs/samples for every language. So, no promises - it might be a while. I'm going to close this for now, but let us know if you find an issue with another sample.

In the meantime, this sounds like a great Community article, to host on https://cloud.google.com/community. Anyone and everyone is welcome to write a Community Tutorial - you can find out how at https://cloud.google.com/community/tutorials/write.
