### ISSUE TITLE
testing: don't set github status for child jobs

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/golang-samples#664]
Kokoro's github status should only be set for the parent job (i.e., whether all child jobs succeeded). Currently, each child job sets a github status, and then after the last one completes, the parent job sets the status again.

This shows the status as green in the following situation:

Job 1: green
Job 2: green
Job 3: red
Parent job: red

Until Job 3 finishes, the status is set to green.

**Comment by tbpg** [comment]
Fixed internally.
