### ISSUE TITLE
testing: enhance gimmeproj to support scripting changes across projects

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/golang-samples#669]
When making a change to the setup of projects, it's fairly common to implement something like this:

```
gcloud config set project golang-samples-tests
gcloud <my project change>

for i in {2..10}; do
  gcloud config set project golang-samples-tests-$i
  gcloud <my project change>
done

gcloud config set project $GOOGLE_CLOUD_PROJECT
```

That change seems like it could easily be facilitated, and avoid the need to know the naming conventions of the underlying project.

## Solution Options

These options are not mutually exclusive.

### Option A: Listing Projects

`gimmeproj list` provides an iterable list of the projects. This would include the meta project, and allow for scripting like so:

```
for $proj in $(gimmeproj list); do foo $proj; done
```

**Pros:** Versatile, Low maintenance
**Cons:** Not Terse, More Scripting Required, Usage Samples Needed

### Option B: Execution Wrapper

```
gimmeproj exec <foo>
gimmeproj exec --file=<foo>
```

In this case, gimmeproj wraps your one-liner or script in it's own for loop.
Project wrangling could be done by injecting $GOOGLE_PROJECT_NAME as an environment variable, and/or by explicitly calling `gcloud config set project $GOOGLE_PROJECT_NAME` before running the command.

Future enhancements could facilitate output aggregation, impose confirmation steps, and so on.

**Pros:** Smooth Experience, Minimal Memorization
**Cons:** Higher Maintenance Overhead

**Comment by tbpg** [comment]
I like option A. I'm not sure I would use option B to run things. But, maybe it would encourage checking in a project-setup script.

**Comment by grayside** [comment]
They aren't mutually exclusive, and either way list seems valuable. Taking a run at it.
