### ISSUE TITLE
cloudsql: Add TLS example

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/golang-samples#68]

**Comment by odeke-em** [comment]
There doesn't seem to be a package for cloudSQL under any of:
- https://godoc.org/google.golang.org/api
- https://github.com/GoogleCloudPlatform/golang-samples
- https://godoc.org/cloud.google.com/go
and under https://cloud.google.com/sql/docs/apis there are only API clients for:
- .NET
- Java
- Python
<img width="1041" alt="screen shot 2017-08-27 at 10 17 27 am" src="https://user-images.githubusercontent.com/4898263/29751881-0d0e2080-8b11-11e7-9ff6-08ea08a3ebb9.png">

Perhaps we need to first make a package for it

**Comment by odeke-em** [comment]
Oh nvm the package seems to be called `sqladmin` not `cloudsql`

**Comment by odeke-em** [comment]
Oh nvm the package seems to be called sqladmin not cloudsql, but nonetheless we don't seem to have a package under either of these two:
- https://github.com/GoogleCloudPlatform/google-cloud-go
- https://github.com/GoogleCloudPlatform/golang-samples 
but only under
- https://godoc.org/google.golang.org/api/sqladmin

**Comment by jabubake** [comment]
FYI @kurtisvg

**Comment by tbpg** [comment]
Closing this in favor of sample tracker tracking.
