### ISSUE TITLE
logging: re-enable simplelog test

### ISSUE THREAD

**Issue by tbpg** [GoogleCloudPlatform/golang-samples#696]
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/logging/simplelog/simplelog_test.go

**Comment by tbpg** [comment]
Hasn't happened recently. Closing.

**Comment by tbpg** [comment]
https://source.cloud.google.com/results/invocations/d2d4a99f-d7b7-4f46-b4e1-f1c1019089aa/targets/gopath%2Fsrc%2Fgithub.com%2FGoogleCloudPlatform%2Fgolang-samples/tests

Been happening more often recently.

**Comment by tbpg** [comment]
Hasn't happened recently.

**Comment by grayside** [comment]
Test is currently skipped

**Comment by tbpg** [comment]
That would do it!
