### ISSUE TITLE
Out of date instructions in endpoint/getting-started-grpc

### ISSUE THREAD

**Issue by jonasdebeukelaer** [GoogleCloudPlatform/golang-samples#714]
Hey, 

Just thought I'd mention the README in`endpoints/getting-started-grpc` is out of date in two places:

`cloud container builds submit --tag gcr.io/YOUR_PROJECT_ID/go-grpc-hello:1.0 .`
has changed to 
`cloud builds submit --tag gcr.io/YOUR_PROJECT_ID/go-grpc-hello:1.0 .`

and `gci-stable` image doesn't exist anymore. instead I used `cos-stable` from the `cos-cloud` project successfully. So I would suggest changing the line:
`gcloud compute instances create grpc-host --image-family gci-stable --image-project google-containers --tags=http-server`
to
`gcloud compute instances create grpc-host --image-family cos-stable --image-project cos-cloud --tags=http-server`

Cheers,

Jonas

**Comment by jonasdebeukelaer** [comment]
Actually just fixing this myself, ignore this

**Comment by tbpg** [comment]
Thank you! In the future, feel free to open an issue and a PR, then reference the issue from the PR description with something like `Fixes #714`, which will automatically close the issue when the PR is submitted. :)

**Comment by jonasdebeukelaer** [comment]
ah ok will do next time 👍
