### ISSUE TITLE
functions: deploy times out and fails without a helpful error message

### ISSUE THREAD

**Issue by wmark** [GoogleCloudPlatform/golang-samples#749]
I am trying to deploy the *spanner* example—although I suspect this applies to other as well—verbatim, which fails without a sensible error message.

I suspect it's because one of the many dependencies fail to download.

```console
$ cd functions/spanner
$ gcloud functions deploy HelloSpanner \
  --region=us-central1 --memory=128MB --runtime go111 --trigger-http

Deploying function (may take a while - up to 2 minutes)...failed.
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: go: finding cloud.google.com/go v0.34.0
go: downloading cloud.google.com/go v0.34.0
go: finding github.com/golang/protobuf/ptypes/wrappers latest
go: finding google.golang.org/api/iterator latest
# … long list of packages omitted but the last line:
go: finding golang.org/x/net v0.0.0-20180724234803-3673e40ba225
go: finding github.c
```

Changing `v0.34.0` to the most recent `v0.35.1` doesn't help, and doesn't seem to reduce dependencies.

**Comment by tbpg** [comment]
Thank you for the bug report. We're working on speeding this up in a few different ways. I recorded this feedback as further motivation. In the meantime, you can vendor your dependencies to avoid having the builder download them for you. Please note, if you'd like to use modules to manage your vendor directory, modules are preferred by the builder over vendor. So, you should add `go.mod` to a `.gcloudignore` file so `go.mod` isn't uploaded when you run `gcloud deploy`. See https://cloud.google.com/functions/docs/concepts/go-runtime#specifying_dependencies.

I'm going to close this issue, but know we're working on it.

**Comment by tbpg** [comment]
I'm thinking something similar for pre-loading. There are a couple other ideas in the works, too.

Thanks. Yes, we'll definitely improve the error.

Thanks, again, for reporting this. Let us know if there are more issues with the samples.

**Comment by bboughton** [comment]
> I'm going to close this issue, but know we're working on it.

Is there a Case we can watch to get updates on the fix?

**Comment by tbpg** [comment]
Give it a try now. :) Deployments should be much faster when depending on cloud.google.com/go. Also, error messages should hopefully be more helpful now, too.

**Comment by lwsanty** [comment]
@tbpg any updates on this issue?

I still have the same error.

I could have used a vendor mode solution, but have local dependencies inside the repo, that are not included in the vendor and thus I have an error on vendor mode
```go
Build failed: srv/gopath/src/p/vendor/metadata/github_client.go:6:2: cannot find package "github.com/xxx/metadata/github" in any of:
```

**Comment by tbpg** [comment]
Could you share a (public) version (Go code + `go.mod`) of a function you're having a problem with? I just deployed a function with a few dependencies and didn't have any issues.

**Comment by lwsanty** [comment]
@tbpg during the deployment of any CF from this repo https://github.com/athenianco/metadata

**Comment by tbpg** [comment]
Unfortunately (?), I was able to deploy a function with the same `go.mod`. This was the command I used:

```
gcloud functions deploy MyFunction --runtime go113 --trigger-http --allow-unauthenticated
```

But, we are definitely aware that some of the build failures are completely unhelpful. We're working on it. No promises on timeline, but it's on the way.
