### ISSUE TITLE
Functions example doesn't work

### ISSUE THREAD

**Issue by korjavin** [GoogleCloudPlatform/golang-samples#761]
I follow https://cloud.google.com/functions/docs/quickstart#functions-clone-sample-repository-go

I cloned repository and run:

gcloud functions deploy HelloGet --runtime go111 --trigger-http                                                 

I've got:
```
Created .gcloudignore file. See `gcloud topic gcloudignore` for details.
Deploying function (may take a while - up to 2 minutes)...failed.                                                                                            
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: # serverlessapp
/tmp/sgb/gopath/src/serverlessapp/worker.go:48:28: undefined: samples.HelloGet
/tmp/sgb/gopath/src/serverlessapp/worker.go:173:29: undefined: samples.HelloGet
```

**Comment by broady** [comment]
Did you run that command from the `helloworld` directory? Can you provide a full log of what you did and ran?

**Comment by tbpg** [comment]
Thanks for filing this issue. I checked over the instructions again and they seem right. So, I'm going to close this for now.

**Comment by tmac33** [comment]
I have encountered this situation, 
most likely your command terminal did not set the Gopath.
