### ISSUE TITLE
Unable to get stackdriver logging working in GAE Second Generation standard (Golang)

### ISSUE THREAD

**Issue by user2657** [GoogleCloudPlatform/golang-samples#773]
I tried following exactly on golang-samples/logging/logging_quickstart/main.go to test out the logging client but that didn't work in both GAE production (using default credentials) and local GO (using JSON credential file) environment.

On https://console.cloud.google.com/logs/viewer, nothing is logged except for the stdout which is generate from the following line while running on GAE:

`fmt.Printf("Logged: %v\n", text)`

On the console I have selected "All logs" from the drop down box, also there is no "my-log" entry in the dropdown box.

No error message were generated from the following lines, probably err was nil:
```
log.Fatalf("Failed to create client: %v", err)
log.Fatalf("Failed to close client: %v", err)
```

Since there no errors that leave me no clue what's going on and what's wrong...

**Comment by tbpg** [comment]
Sorry for the trouble and slow response. I tested this out and it worked. Be sure to select "Google Project" from the dropdown at the top left.
![logging](https://user-images.githubusercontent.com/26876514/59281037-97887000-8c34-11e9-9b34-cd33efd011ca.png)
