### ISSUE TITLE
container_registry/container_analysis: TestUpdateOccurrence flaky

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/golang-samples#785]
Tracking bug.

Possibly related to #603.

**Comment by DanSanche** [comment]
This is on my to-do list, but the last week has been a bit busy for Next. If this is blocking anything, let me know and I'll bump up the priority

**Comment by broady** [comment]
not blocking anything, the test is disabled

**Comment by DanSanche** [comment]
I removed this sample/test to limit the sample surface area going in to GA, since it isn't currently used in the docs
