### ISSUE TITLE
all: docs say to use iterator.Done without saying where to find it

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/golang-samples#791]
A lot of our godocs mention "iterator.Done" without saying the path to the iterator package.

e.g., https://godoc.org/cloud.google.com/go/spanner

/cc @noahdietz @jadekler

**Comment by noahdietz** [comment]
Similar to [gapic-generator #2620](https://github.com/googleapis/gapic-generator/issues/2620) and could be solved with the same approach. Shall we add `iterator` to the types we "identify" with a comment in the generated snippets?

**Comment by jadekler** [comment]
Maybe it could be solved with a cloud.google.com/go level comment about iterators? We have a similar thing for the option package.

**Comment by broady** [comment]
@noahdietz Yep, I think so. Let's decide on a style and go with it everywhere. I wonder if we can automate/tool for this across all examples?

@jadekler top-level is good, but one level of indirection for something that is really core to the packages that have iterators

**Comment by broady** [comment]
Mistakenly filed in wrong repo. Moved to googleapis/google-cloud-go#1356
