### ISSUE TITLE
getting-started/bookshelf: add separate template blocks for title+body

### ISSUE THREAD

**Issue by zemirco** [GoogleCloudPlatform/golang-samples#8]
Thank you for the great examples!

Could you add independent titles to the bookshelf app? I.e.

base.html

``` go
<title>
  {{ template "title" . }}
</title>
```

detail.html

``` go
{{ define "title" }}
  Detail
{{ end }}

{{ define "body" }}
...
{{ end }}
```

At the moment that doesn't work because all the included template content is put into "body". I'm having trouble finding an elegant solution with `ParseGlob`.

Any hints?

**Comment by broady** [comment]
Yes, this is rather difficult. I may change the templates to `{{ define "body" }}`.

In Go 1.6, we get template blocks, which are very useful for this!

**Comment by zemirco** [comment]
Any news on this issue?

Cheers!

**Comment by broady** [comment]
@zemirco Nope, haven't had a look at it yet. I'll try to look some time this week.

Happy to take a pull request if you already have a reasonable approach, though!

**Comment by tbpg** [comment]
Declaring bankruptcy on this issue. Sorry we never got to it! Go 1.6 has long been released, so hopefully this is a bit easier.
