### ISSUE TITLE
functions: create a sample of writing a log with a severity

### ISSUE THREAD

**Issue by mvndaai** [GoogleCloudPlatform/golang-samples#802]
The [docs](https://cloud.google.com/functions/docs/monitoring/logging#functions-log-retrieve-go) say that 
> Logs to stdout or stderr do not have an associated log level.

Then later say 
> Logs can also be written and retrieved through the Logging API

There is a sample of [retrieving](https://github.com/GoogleCloudPlatform/golang-samples/blob/master/functions/log/list.go) logs, but I cannot find a way to write them with a severity level.

In Kubernetes deployed servers I can set the severity level by printing a JSON object like this.
```golang
fmt.Println({ "message" : "msg", "severity": "info" })
```
But in cloud functions even if the payload is JSON, stackdriver logs always consider it a `textPayload`.

It would be nice if those docs could be updated to include a sample of how to include log levels in Cloud Functions.

**Comment by tbpg** [comment]
You can log with severity using the [(*logging.Logger).Log](https://godoc.org/cloud.google.com/go/logging#Logger.Log) function, where you have control over the complete log entry.

@stew-r or @ace-n, any ideas on the right way to document this?

**Comment by mvndaai** [comment]
If it helps, I made a package to help me with this https://godoc.org/github.com/mvndaai/cflog .
It was pretty complicated to set up since I needed to create a client that matched a cloud functions environment, know the severity codes, and know how to handle JSON payloads vs text payloads (I didn't do protobufs yet). 

My package might have performance issues because I am not batch uploading the logs. Also if there is an error using the client, I opt, most of the time, to just use `log.Printf` which means things will be in the logs, but the severity is 0, which makes them hard to find.

**Comment by grayside** [comment]
Structured logging with severity should in theory be much the same between Cloud Functions and Cloud Run. I'm currently working on a Nodejs sample for logging on Cloud Run with severity but without a client library. It didn't seem especially valuable to cover basics of serialized JSON handling in all the languages.

Using Go to log to stackdriver with the client library is documented in https://cloud.google.com/logging/docs/setup/go.

@mvndaai what inspired you to create that package? Is it unclear how to use the logging library on Cloud Functions? Too complicated? Something else?

**Comment by mvndaai** [comment]
@grayside the reason for the package was for easy log severity in google cloud functions.

Setting up the logging client to match the space of a cloud functions `log.Println()` while allowing me to choose `INFO` or `ERROR` severity was hard to do. That being said I hadn't seen `.StandardLogger(logging.Info)` which might make it easier. I will have to try that. Thank you.

I was more confused about why I needed to use the logging library at all. At my work, we have a kubernetes setup and when logs to stdout can be interpreted as a `logging.Entry` it is. Having to set up a client at all means that if there are errors with the error client they might get logged to stderr which has no severity and would get lost under debug logs.

**Comment by grayside** [comment]
Thank you for clarifying. Cloud Functions may get this functionality (write JSON to stdout, set severity as a property) in the future.

**Comment by kaihendry** [comment]
I'm trying to simply log JSON so that it appears structured in stackdriver.

I must say https://github.com/GoogleCloudPlatform/golang-samples/blob/master/logging/simplelog/simplelog.go is far from simple. And it puzzles my why I need to put the [PROJECT_ID to even use the logger](https://cloud.google.com/logging/docs/setup/go). Bizaare.

**Comment by ace-n** [comment]
cc @vinod-at-google

**Comment by grant** [comment]
I think CCing @juliehockett would be best for understanding the state of logging severity with Go in GCF.

**Comment by tbpg** [comment]
Related to https://github.com/googleapis/google-cloud-go/issues/1656.

**Comment by tbpg** [comment]
@mvndaai, will you try logging with JSON now? We recently enabled structured logging support in Cloud Functions, so I'm hoping it works for you.

**Comment by tbpg** [comment]
You can now log JSON messages to stdout and they will be parsed as JSON. For example:

```
fmt.Println(`{ "message" : "msg", "severity": "error" }`)
```

I'm looking into getting the docs updated, but I'm going to close this particular issue.

**Comment by tbpg** [comment]
On second thought, we can improve the logging sample to show this. PR coming up.
