### ISSUE TITLE
jobs/v4: TestHistogramSearch is failing

### ISSUE THREAD

**Issue by tbpg** [GoogleCloudPlatform/golang-samples#822]
Line 4180 of https://source.cloud.google.com/results/invocations/f860af24-65c1-42b2-9391-4c34b8fa3f99/targets/cloud-devrel%2Fgo%2Fgolang-samples%2Fsystem-tests%2Fgo112/log:
```
--- FAIL: TestHistogramSearch (13.59s)
    retry.go:44: FAILED after 10 attempts:
        histogram_search_sample_test.go:36: histogramSearch got "Job: \"projects/golang-samples-tests-4/tenants/null/jobs/132306366103462598\"\n", want to contain "projects/golang-samples-tests-4/tenants/547c9536-cd00-0000-0000-00b36ca93e2a/jobs/132306366103462598"
```

I'll disable the test and this issue will be used to track re-enabling it.

**Comment by anguillanneuf** [comment]
@chenlei1216 should we expect more tests to fail with changes coming to v4beta1?
