### ISSUE TITLE
How to manage client connection in API

### ISSUE THREAD

**Issue by pierrebiver** [GoogleCloudPlatform/golang-samples#833]
I'm using different google's services in Go and this is unclear to me whether I should close the connection every time I make a call or if I can reuse the same client concurrently. 
Could it be stated clearly in the documentation?

**Comment by tbpg** [comment]
In general, you can reuse the same client concurrently. If there are concurrency considerations to keep in mind, they will be documented on the method/function.

It's common to create a single client (say, during app initialization) then reuse it for the life of the application. This is also useful for something like Cloud Functions - you can initialize the client during cold starts then re-use it for subsequent executions. See https://cloud.google.com/functions/docs/bestpractices/tips#do_lazy_initialization_of_global_variables.
