### ISSUE TITLE
Sample for Go using gRPC response service fail

### ISSUE THREAD

**Issue by SantyTaco** [GoogleCloudPlatform/golang-samples#841]
I trying to deploy a service using go and grpc. I am using this tutorial https://github.com/GoogleCloudPlatform/golang-samples/tree/master/endpoints/getting-started-grpc and everything was complete successful until I have to call the service.

In the moment that I use the client to call the service I get this error:

``could not greet: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 35.199.74.154:80: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because
connected host has failed to respond.``

**Comment by tbpg** [comment]
Hi @SantyTaco. Were you running the server locally, on GCE, or GKE? I tried it locally and on GCE and it worked.

**Comment by tbpg** [comment]
@SantyTaco, if you were running on GCE, would you mind trying with the changes from #845?

**Comment by tbpg** [comment]
Closing this as it's been ~1 month. Thank you for filing this issue and hopefully you got it working!
