### ISSUE TITLE
Trace quickstart: propagation.HTTPFormat is an interface, code doesn't compile

### ISSUE THREAD

**Issue by subwiz** [GoogleCloudPlatform/golang-samples#869]
The quickstart example for Trace has an initialization code:

```go
propagation.HTTPFormat{}
```

This is failing, as `propagation.HTTPFormat` is an interface.

**Comment by subwiz** [comment]
Sorry, got mixed up with the import.

I was not importing `contrib.go.opencensus.io/exporter/stackdriver/propagation`.

**Comment by tbpg** [comment]
Thanks for the report - glad you got it figured out. Let us know if you run into any other problems!
