### ISSUE TITLE
bigquery: createTableWithCMEK flaky

### ISSUE THREAD

**Issue by tbpg** [GoogleCloudPlatform/golang-samples#872]
> snippet_test.go:139: createTableWithCMEK(dataset:"golang_example_dataset_1559668279" table:"golang_example_table_cmek_1559668310"): googleapi: Error 409: Already Exists: Table golang-samples-tests-8:golang_example_dataset_1559668279.golang_example_table_cmek_1559668310, duplicate

https://source.cloud.google.com/results/invocations/8c553692-f8dc-4362-8160-37add6a6fcea/targets/gopath%2Fsrc%2Fgithub.com%2FGoogleCloudPlatform%2Fgolang-samples/tests

**Comment by tbpg** [comment]
Maybe `uniqueBQName` should use a UUID? Or maybe a retry reused the same table?

**Comment by shollyman** [comment]
Looking at this one, I think this was some form of retry.  Checking fusion I'm not seeing this persistently, unless I'm missing something. The table prefix is unique for the test, so it's either retry or collisions from multiple test runs in the same project.

**Comment by shollyman** [comment]
Going to close this one.  It doesn't improve the sample readability to expose custom logic for the rare "insert-succeeded-but-response-failed" case followed by a 409 duplicate on retry.
