### ISSUE TITLE
functions: enable imagemagick and redis tests

### ISSUE THREAD

**Issue by tbpg** [GoogleCloudPlatform/golang-samples#877]
We skip the test right now because `convert` is not available in the test images. We should add it to the images and enable the test.

**Comment by tbpg** [comment]
See #868 for adding a Redis sample.

**Comment by grayside** [comment]
As an alternative, we could create a simulated GCF Go runtime container and use that for system tests like this. It would also facilitate testing future function-framework based samples on Cloud Run.
