### ISSUE TITLE
appengine_flexible: Cloud SQL and Datastore samples should only store first two Octets of IP

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/golang-samples#9]
Principle of least required data retention.

**Comment by broady** [comment]
Perhaps there's something more interesting we can store.

**Comment by jabubake** [comment]
@kurtisvg @ryanmats FYI

**Comment by tbpg** [comment]
I looked around but didn't see which sample this was referring to (and didn't find relevant mentions of `IP`). Closing as obsolete (sample moved/changed?)

**Comment by tbpg** [comment]
One example: https://github.com/GoogleCloudPlatform/golang-samples/blob/master/appengine_flexible/cloudsql/cloudsql.go#L98-L102
