### ISSUE TITLE
bigtable: re-enable garbage collection test

### ISSUE THREAD

**Issue by tbpg** [GoogleCloudPlatform/golang-samples#914]
It's flaky right now. Example failure: https://source.cloud.google.com/results/invocations/0e9abfbf-9c9f-4b87-8631-888653b5d76e/targets/gopath%2Fsrc%2Fgithub.com%2FGoogleCloudPlatform%2Fgolang-samples/tests.

**Comment by billyjacobson** [comment]
Fixed by https://github.com/GoogleCloudPlatform/golang-samples/pull/998
