### ISSUE TITLE
speech: consider moving to cloud.google.com/go/speech/apiv1

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/golang-samples#93]
A nicer Speech API client is available at cloud.google.com/go/speech/apiv1 that helps the users with initialization of the gRPC connection. We should consider switching to it once it is mature.

**Comment by broady** [comment]
Unfortunately it's the wrong API. We need to use `apiv1beta`. Responded over at the [CL](https://code-review.googlesource.com/#/c/7150/2).

/cc @pongad @jba
