### ISSUE TITLE
functions/codelabs/gopher: tree is not installed by default

### ISSUE THREAD

**Issue by alicemerrick** [GoogleCloudPlatform/golang-samples#948]
UX issue: The codelab recommends using Cloud Shell but references the tree command at the bottom of step 2 of the tutorial, which does not come with Cloud Shell out of the box. I would recommend providing link/instructions on how to install it or at least note that it doesn't come with Cloud Shell.
![image](https://user-images.githubusercontent.com/26319413/63203927-81899800-c047-11e9-9664-1516352c5b23.png)

**Comment by tbpg** [comment]
Thank you for reporting this! I updated the snippet to include installing `tree`:

```
$ sudo apt-get install tree # Optional.
$ tree # Optional.
.
├── cmd
│   └── main.go     # Binary to run the function locally.
├── go.mod          # Go module definition.
├── gophercolor.png # The gopher!
├── gopher.go       # Go file with the function.
└── gopher_test.go  # Go test file.

```
