### ISSUE TITLE
compute: example on create Compute Instances

### ISSUE THREAD

**Issue by moos3** [GoogleCloudPlatform/golang-samples#965]
It would be wonderful if there was a series of examples around the Compute API. Mainly creating an instance without metadata and one with metadata. This would be extremely helpful to the community.

**Comment by tbpg** [comment]
Sorry for the slow response. Have you seen this page? https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert

There is a small sample at the bottom. You can set metadata in the `instance` you pass as an argument to `Insert`.

**Comment by tbpg** [comment]
Going to close this for now. Hopefully that insert link gets you started! We may have a larger rewrite of the Compute samples in the future.
