### ISSUE TITLE
appengine/go11x/tasks: ScheduleTime not included

### ISSUE THREAD

**Issue by zaddok** [GoogleCloudPlatform/golang-samples#970]
In some languages `ScheduleTime` on a task is demonstrated, but in golang it is not.

It is not made clear if this means we can't use `ScheduleTime` or if it is just not documented here.

https://github.com/GoogleCloudPlatform/golang-samples/blob/02e03864828e17ba3e86db114679d9521a737581/appengine/go11x/tasks/create_task/create_task.go#L57

I've worked out how to do it, does this project take pull requests?

**Comment by tbpg** [comment]
Thanks for filing this issue! Yes, feel free to send a pull request. Thank you!

(See https://github.com/GoogleCloudPlatform/golang-samples/blob/master/CONTRIBUTING.md for instructions for contributing. In particular, the CLA.)
