### ISSUE TITLE
appengine/flexible: use split health checks

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/golang-samples#977]
From deploying helloworld:

> GAE Flex legacy health check is deprecated and its support will end soon. Please migrate to updated health checks. See https://cloud.google.com/appengine/docs/flexible/python/reference/app-yaml#updated_health_checks for instructions.

**Comment by tbpg** [comment]
We don't have any `health_check` sections in `app.yaml` files. So, there is nothing to configure there.

However, we do have several `/_ah/health` handlers that are currently not doing anything.

Split health checks are not automatically forwarded to apps. So, I propose we delete the existing legacy health check handlers and do not add handlers for the new split checks.
