### ISSUE TITLE
go11x/static fails with Error: Server Error

### ISSUE THREAD

**Issue by Deleplace** [GoogleCloudPlatform/golang-samples#993]
```
$ git clone https://github.com/GoogleCloudPlatform/golang-samples.git
$ cd golang-samples/appengine/go11x/static
```
ok
```
$ go version
go version go1.13 linux/amd64
$ go run .
2019/09/20 17:51:01 Defaulting to port 8080
2019/09/20 17:51:01 Listening on port 8080
```
ok, local server works fine
```
$ gcloud app deploy
```
ok, provided some account and project are set, and some Cloud Build API is enabled.

```
$ gcloud app browse
```
**Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds.**

In the Stackdriver Loggind web view:

```
panic: open templates/index.html: no such file or directory
```

**Comment by Deleplace** [comment]
The expectation is that if it runs locally and deploys without error, then it should run fine.

The above steps were performed **outside my gopath**. And there is no `go.mod` file in the `static` project.

Now if I do the same inside my gopath i.e. at `~/go/src/github.com/GoogleCloudPlatform/golang-samples/appengine/go11x/static`, the deployed app works fine.

I acknowledge that some folder path weirdness may be already known depending on modules/no modules and inside/outside gopath, but the root cause and the solution look currently non-obvious and non-discoverable in the `GoogleCloudPlatform/golang-samples` GitHub repo. The app behaves differently locally and in production. The platform "looks broken" and this is an extra burden for folks trying to migrate existing apps to go111 or go112.

In an ideal world, the path problem would be fixed by GCP and my deployment would "just work".
In an slightly ideal world, `gcloud app deploy` should be aware that something is wrong and fail early.
If not feasible, then a `README` should clearly state that the project must reside locally inside the GOPATH.

@tbpg

**Comment by tbpg** [comment]
If we add a `go.mod` to the sample, it should fix the problem. I sent #995 to add one (and a test). Go Modules are supported in Go 1.11+, and GAE Standard is second gen for Go 1.11+, so we don't have to worry about not having modules support in the Go version people are using.

Thank you for filing this!

**Comment by Deleplace** [comment]
Thank you Tyler and Jean
